# Generated by Django 6.0.2 on 2026-05-06 11:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('asset_type', models.CharField(choices=[('furniture', 'Furniture'), ('electronics', 'Electronics'), ('appliances', 'Appliances'), ('fixtures', 'Fixtures & Fittings'), ('linen', 'Linen & Textiles'), ('amenities', 'Amenities'), ('decor', 'Decor Items'), ('security', 'Security Equipment'), ('other', 'Other')], default='furniture', max_length=50)),
                ('default_depreciation_method', models.CharField(choices=[('straight_line', 'Straight Line'), ('declining_balance', 'Declining Balance'), ('double_declining', 'Double Declining Balance'), ('units_of_production', 'Units of Production'), ('none', 'No Depreciation')], default='straight_line', max_length=50)),
                ('default_useful_life_years', models.PositiveIntegerField(default=5, help_text='Default useful life in years')),
                ('default_salvage_value_percent', models.DecimalField(decimal_places=2, default=10.0, help_text='Default salvage value as percentage of purchase price', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_categories', to='hotels.hotel')),
            ],
            options={
                'verbose_name_plural': 'Asset Categories',
                'ordering': ['name'],
                'unique_together': {('hotel', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RoomAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Asset name/description', max_length=200)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('model_number', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_date', models.DateField(help_text='Date of purchase')),
                ('purchase_price', models.DecimalField(decimal_places=2, help_text='Original purchase price', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('current_value', models.DecimalField(decimal_places=2, default=0, help_text='Current depreciated value', max_digits=12)),
                ('depreciation_method', models.CharField(choices=[('straight_line', 'Straight Line'), ('declining_balance', 'Declining Balance'), ('double_declining', 'Double Declining Balance'), ('units_of_production', 'Units of Production'), ('none', 'No Depreciation')], default='straight_line', max_length=50)),
                ('useful_life_years', models.PositiveIntegerField(default=5, help_text='Useful life in years for depreciation')),
                ('salvage_value', models.DecimalField(decimal_places=2, default=0, help_text='Estimated salvage/residual value', max_digits=12)),
                ('last_depreciation_date', models.DateField(blank=True, help_text='Last date depreciation was calculated', null=True)),
                ('total_depreciation', models.DecimalField(decimal_places=2, default=0, help_text='Total depreciation accumulated', max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Under Maintenance'), ('broken', 'Broken/Unusable'), ('disposed', 'Disposed'), ('stolen', 'Stolen'), ('lost', 'Lost')], default='active', max_length=50)),
                ('purchase_invoice', models.FileField(blank=True, null=True, upload_to='asset_invoices/%Y/%m/')),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='rooms.assetcategory')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_assets', to='hotels.hotel')),
                ('room', models.ForeignKey(blank=True, help_text='Specific room this asset belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='rooms.room')),
                ('room_type', models.ForeignKey(blank=True, help_text='Room type template (for assets common to all rooms of this type)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='rooms.roomtype')),
            ],
            options={
                'ordering': ['-purchase_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AssetDepreciationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_date', models.DateField(auto_now_add=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('depreciation_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, max_digits=12)),
                ('book_value_before', models.DecimalField(decimal_places=2, max_digits=12)),
                ('book_value_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_schedule', to='rooms.roomasset')),
            ],
            options={
                'ordering': ['-calculation_date'],
            },
        ),
        migrations.CreateModel(
            name='RoomLiability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('liability_type', models.CharField(choices=[('loan', 'Loan/Mortgage'), ('maintenance', 'Maintenance Debt'), ('renovation', 'Renovation Cost'), ('supplier', 'Supplier Debt'), ('tax', 'Tax Liability'), ('insurance', 'Insurance Premium'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('remaining_balance', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, help_text='Annual interest rate (%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('start_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('payment_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually'), ('one_time', 'One Time')], default='monthly', max_length=20)),
                ('monthly_payment', models.DecimalField(decimal_places=2, default=0, help_text='Calculated monthly payment', max_digits=12)),
                ('next_payment_date', models.DateField(blank=True, null=True)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('overdue', 'Overdue'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_liabilities', to='hotels.hotel')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liabilities', to='rooms.room')),
                ('room_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liabilities', to='rooms.roomtype')),
            ],
            options={
                'verbose_name_plural': 'Room Liabilities',
                'ordering': ['-start_date', 'status'],
            },
        ),
        migrations.CreateModel(
            name='LiabilityPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('liability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='rooms.roomliability')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.AddIndex(
            model_name='roomasset',
            index=models.Index(fields=['hotel', 'room'], name='rooms_rooma_hotel_i_48a73f_idx'),
        ),
        migrations.AddIndex(
            model_name='roomasset',
            index=models.Index(fields=['hotel', 'room_type'], name='rooms_rooma_hotel_i_d7a759_idx'),
        ),
        migrations.AddIndex(
            model_name='roomasset',
            index=models.Index(fields=['status'], name='rooms_rooma_status_d0ba21_idx'),
        ),
        migrations.AddIndex(
            model_name='roomasset',
            index=models.Index(fields=['purchase_date'], name='rooms_rooma_purchas_240c84_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assetdepreciationschedule',
            unique_together={('asset', 'period_start', 'period_end')},
        ),
        migrations.AddIndex(
            model_name='roomliability',
            index=models.Index(fields=['hotel', 'room'], name='rooms_rooml_hotel_i_694483_idx'),
        ),
        migrations.AddIndex(
            model_name='roomliability',
            index=models.Index(fields=['status'], name='rooms_rooml_status_b59bd5_idx'),
        ),
        migrations.AddIndex(
            model_name='roomliability',
            index=models.Index(fields=['due_date'], name='rooms_rooml_due_dat_61e6ea_idx'),
        ),
    ]
