# Generated by Django 6.0.2 on 2026-04-17 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_hotelamenity_hotelcategory_hotelchain_and_more'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload room image (JPG, PNG, WebP recommended)', upload_to='room_images/%Y/%m/%d/')),
                ('category', models.CharField(choices=[('overall', 'Overall View'), ('bedroom', 'Bedroom Area'), ('bathroom', 'Bathroom'), ('view', 'Window/View'), ('amenities', 'Amenities'), ('seating', 'Seating Area'), ('workspace', 'Workspace'), ('closet', 'Closet/Storage'), ('balcony', 'Balcony/Terrace'), ('other', 'Other')], default='overall', help_text='Category of the room image', max_length=50)),
                ('title', models.CharField(blank=True, help_text='Image title for display', max_length=255, null=True)),
                ('alt_text', models.CharField(blank=True, help_text='SEO alternative text', max_length=255, null=True)),
                ('caption', models.TextField(blank=True, help_text='Image caption/description', null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_primary', models.BooleanField(default=False, help_text='Set as primary image for this room')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured in room gallery/listing')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this image is active and visible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_size', models.IntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('width', models.IntegerField(blank=True, help_text='Image width in pixels', null=True)),
                ('height', models.IntegerField(blank=True, help_text='Image height in pixels', null=True)),
                ('hotel', models.ForeignKey(help_text='Hotel this image belongs to (denormalized for faster queries)', on_delete=django.db.models.deletion.CASCADE, related_name='room_images', to='hotels.hotel')),
                ('room', models.ForeignKey(help_text='Room this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rooms.room')),
                ('room_type', models.ForeignKey(blank=True, help_text='Room type this image represents (for gallery purposes)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rooms.roomtype')),
            ],
            options={
                'verbose_name': 'Room Image',
                'verbose_name_plural': 'Room Images',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomImageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Gallery name (e.g., 'Deluxe Suite Views')", max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Gallery description', null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(help_text='Hotel this gallery belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='image_galleries', to='hotels.hotel')),
                ('images', models.ManyToManyField(blank=True, help_text='Images in this gallery', related_name='galleries', to='rooms.roomimage')),
                ('room_type', models.ForeignKey(blank=True, help_text='Room type this gallery is for (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='rooms.roomtype')),
            ],
            options={
                'verbose_name': 'Room Image Gallery',
                'verbose_name_plural': 'Room Image Galleries',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='roomimage',
            index=models.Index(fields=['room', 'is_primary'], name='rooms_roomi_room_id_ef6514_idx'),
        ),
        migrations.AddIndex(
            model_name='roomimage',
            index=models.Index(fields=['room_type', 'is_featured'], name='rooms_roomi_room_ty_83ec5e_idx'),
        ),
        migrations.AddIndex(
            model_name='roomimage',
            index=models.Index(fields=['hotel', 'is_active'], name='rooms_roomi_hotel_i_ba4b86_idx'),
        ),
        migrations.AddIndex(
            model_name='roomimage',
            index=models.Index(fields=['category'], name='rooms_roomi_categor_d5961e_idx'),
        ),
        migrations.AddIndex(
            model_name='roomimage',
            index=models.Index(fields=['order'], name='rooms_roomi_order_bee86a_idx'),
        ),
        migrations.AddIndex(
            model_name='roomimagegallery',
            index=models.Index(fields=['hotel', 'is_active'], name='rooms_roomi_hotel_i_0b961c_idx'),
        ),
        migrations.AddIndex(
            model_name='roomimagegallery',
            index=models.Index(fields=['slug'], name='rooms_roomi_slug_d798e9_idx'),
        ),
    ]
