# Generated by Django 6.0.2 on 2026-07-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_assetcategory_roomasset_assetdepreciationschedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
