# Generated by Django 6.0.2 on 2026-05-02 08:47

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_categories', to='hotels.hotel')),
            ],
            options={
                'ordering': ['hotel__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StoreItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('sku', models.CharField(blank=True, max_length=60, null=True)),
                ('unit', models.CharField(default='pcs', max_length=30)),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('selling_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('stock_qty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('reorder_level', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='store.storecategory')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_items', to='hotels.hotel')),
            ],
            options={
                'ordering': ['hotel__name', 'category__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StorePurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(blank=True, max_length=60, null=True)),
                ('order_date', models.DateField(default=django.utils.timezone.localdate)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('partially_received', 'Partially Received'), ('received', 'Received'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=30)),
                ('note', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_store_purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_store_purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_purchase_orders', to='hotels.hotel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreGoodsReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(blank=True, max_length=60, null=True)),
                ('supplier_invoice_number', models.CharField(blank=True, max_length=120, null=True)),
                ('received_date', models.DateField(default=django.utils.timezone.localdate)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_goods_receipts', to='hotels.hotel')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_store_goods_receipts', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='store.storepurchaseorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StorePurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_ordered', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('received_qty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_items', to='store.storeitem')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.storepurchaseorder')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StoreGoodsReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_received', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('goods_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.storegoodsreceipt')),
                ('purchase_order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_items', to='store.storepurchaseorderitem')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StoreSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_number', models.CharField(blank=True, max_length=60, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=20)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_sales', to='hotels.hotel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreSaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='store.storeitem')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.storesale')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StoreStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('opening', 'Opening'), ('purchase', 'Purchase'), ('issue', 'Issue'), ('sale', 'Sale'), ('adjustment', 'Adjustment'), ('damage', 'Damage'), ('return', 'Return')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('reference', models.CharField(blank=True, max_length=120, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_stock_movements', to='hotels.hotel')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='store.storeitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=150, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('tin_number', models.CharField(blank=True, max_length=60, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_store_suppliers', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_suppliers', to='hotels.hotel')),
            ],
            options={
                'ordering': ['hotel__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='storepurchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='store.storesupplier'),
        ),
        migrations.AddIndex(
            model_name='storecategory',
            index=models.Index(fields=['hotel', 'name'], name='store_store_hotel_i_80f831_idx'),
        ),
        migrations.AddIndex(
            model_name='storecategory',
            index=models.Index(fields=['hotel', 'is_active'], name='store_store_hotel_i_84a653_idx'),
        ),
        migrations.AddConstraint(
            model_name='storecategory',
            constraint=models.UniqueConstraint(fields=('hotel', 'name'), name='uniq_store_category_per_hotel'),
        ),
        migrations.AddIndex(
            model_name='storeitem',
            index=models.Index(fields=['hotel', 'category'], name='store_store_hotel_i_068ee2_idx'),
        ),
        migrations.AddIndex(
            model_name='storeitem',
            index=models.Index(fields=['hotel', 'name'], name='store_store_hotel_i_24ebd4_idx'),
        ),
        migrations.AddIndex(
            model_name='storeitem',
            index=models.Index(fields=['hotel', 'sku'], name='store_store_hotel_i_fd4e39_idx'),
        ),
        migrations.AddIndex(
            model_name='storeitem',
            index=models.Index(fields=['hotel', 'is_active'], name='store_store_hotel_i_50adbb_idx'),
        ),
        migrations.AddConstraint(
            model_name='storeitem',
            constraint=models.UniqueConstraint(fields=('hotel', 'name'), name='uniq_store_item_name_per_hotel'),
        ),
        migrations.AddIndex(
            model_name='storegoodsreceipt',
            index=models.Index(fields=['hotel', 'receipt_number'], name='store_store_hotel_i_fa9f1c_idx'),
        ),
        migrations.AddIndex(
            model_name='storegoodsreceipt',
            index=models.Index(fields=['hotel', 'received_date'], name='store_store_hotel_i_b34ecc_idx'),
        ),
        migrations.AddIndex(
            model_name='storepurchaseorderitem',
            index=models.Index(fields=['purchase_order'], name='store_store_purchas_5c42f6_idx'),
        ),
        migrations.AddIndex(
            model_name='storepurchaseorderitem',
            index=models.Index(fields=['item'], name='store_store_item_id_ebb444_idx'),
        ),
        migrations.AddConstraint(
            model_name='storepurchaseorderitem',
            constraint=models.UniqueConstraint(fields=('purchase_order', 'item'), name='uniq_po_item_per_purchase_order'),
        ),
        migrations.AddIndex(
            model_name='storegoodsreceiptitem',
            index=models.Index(fields=['goods_receipt'], name='store_store_goods_r_d891db_idx'),
        ),
        migrations.AddIndex(
            model_name='storegoodsreceiptitem',
            index=models.Index(fields=['purchase_order_item'], name='store_store_purchas_57d3f3_idx'),
        ),
        migrations.AddIndex(
            model_name='storesale',
            index=models.Index(fields=['hotel', 'status'], name='store_store_hotel_i_5395e5_idx'),
        ),
        migrations.AddIndex(
            model_name='storesale',
            index=models.Index(fields=['hotel', 'created_at'], name='store_store_hotel_i_8782ce_idx'),
        ),
        migrations.AddIndex(
            model_name='storesale',
            index=models.Index(fields=['hotel', 'sale_number'], name='store_store_hotel_i_13984c_idx'),
        ),
        migrations.AddIndex(
            model_name='storesaleitem',
            index=models.Index(fields=['sale'], name='store_store_sale_id_ef7f46_idx'),
        ),
        migrations.AddIndex(
            model_name='storestockmovement',
            index=models.Index(fields=['hotel', 'item'], name='store_store_hotel_i_3d9fef_idx'),
        ),
        migrations.AddIndex(
            model_name='storestockmovement',
            index=models.Index(fields=['hotel', 'movement_type'], name='store_store_hotel_i_31b5f8_idx'),
        ),
        migrations.AddIndex(
            model_name='storestockmovement',
            index=models.Index(fields=['hotel', 'created_at'], name='store_store_hotel_i_976913_idx'),
        ),
        migrations.AddIndex(
            model_name='storesupplier',
            index=models.Index(fields=['hotel', 'name'], name='store_store_hotel_i_4e6a94_idx'),
        ),
        migrations.AddIndex(
            model_name='storesupplier',
            index=models.Index(fields=['hotel', 'is_active'], name='store_store_hotel_i_7eff46_idx'),
        ),
        migrations.AddConstraint(
            model_name='storesupplier',
            constraint=models.UniqueConstraint(fields=('hotel', 'name'), name='uniq_store_supplier_per_hotel'),
        ),
        migrations.AddIndex(
            model_name='storepurchaseorder',
            index=models.Index(fields=['hotel', 'status'], name='store_store_hotel_i_89b789_idx'),
        ),
        migrations.AddIndex(
            model_name='storepurchaseorder',
            index=models.Index(fields=['hotel', 'po_number'], name='store_store_hotel_i_b3dbe6_idx'),
        ),
        migrations.AddIndex(
            model_name='storepurchaseorder',
            index=models.Index(fields=['hotel', 'order_date'], name='store_store_hotel_i_8bd686_idx'),
        ),
    ]
