# Generated by Django 6.0.2 on 2026-03-09 19:20

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_categories', to='hotels.hotel')),
            ],
            options={
                'ordering': ['hotel__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StoreItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('sku', models.CharField(blank=True, max_length=60, null=True)),
                ('unit', models.CharField(default='pcs', max_length=30)),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('selling_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('stock_qty', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('reorder_level', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='store.storecategory')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_items', to='hotels.hotel')),
            ],
            options={
                'ordering': ['hotel__name', 'category__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StoreSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_number', models.CharField(blank=True, max_length=60, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=20)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_sales', to='hotels.hotel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreSaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='store.storeitem')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.storesale')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StoreStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('opening', 'Opening'), ('purchase', 'Purchase'), ('issue', 'Issue'), ('sale', 'Sale'), ('adjustment', 'Adjustment'), ('damage', 'Damage'), ('return', 'Return')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('reference', models.CharField(blank=True, max_length=120, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_stock_movements', to='hotels.hotel')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='store.storeitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='storecategory',
            index=models.Index(fields=['hotel', 'name'], name='store_store_hotel_i_80f831_idx'),
        ),
        migrations.AddIndex(
            model_name='storecategory',
            index=models.Index(fields=['hotel', 'is_active'], name='store_store_hotel_i_84a653_idx'),
        ),
        migrations.AddConstraint(
            model_name='storecategory',
            constraint=models.UniqueConstraint(fields=('hotel', 'name'), name='uniq_store_category_per_hotel'),
        ),
        migrations.AddIndex(
            model_name='storeitem',
            index=models.Index(fields=['hotel', 'category'], name='store_store_hotel_i_068ee2_idx'),
        ),
        migrations.AddIndex(
            model_name='storeitem',
            index=models.Index(fields=['hotel', 'name'], name='store_store_hotel_i_24ebd4_idx'),
        ),
        migrations.AddIndex(
            model_name='storeitem',
            index=models.Index(fields=['hotel', 'sku'], name='store_store_hotel_i_fd4e39_idx'),
        ),
        migrations.AddIndex(
            model_name='storeitem',
            index=models.Index(fields=['hotel', 'is_active'], name='store_store_hotel_i_50adbb_idx'),
        ),
        migrations.AddConstraint(
            model_name='storeitem',
            constraint=models.UniqueConstraint(fields=('hotel', 'name'), name='uniq_store_item_name_per_hotel'),
        ),
        migrations.AddIndex(
            model_name='storesale',
            index=models.Index(fields=['hotel', 'status'], name='store_store_hotel_i_5395e5_idx'),
        ),
        migrations.AddIndex(
            model_name='storesale',
            index=models.Index(fields=['hotel', 'created_at'], name='store_store_hotel_i_8782ce_idx'),
        ),
        migrations.AddIndex(
            model_name='storesale',
            index=models.Index(fields=['hotel', 'sale_number'], name='store_store_hotel_i_13984c_idx'),
        ),
        migrations.AddIndex(
            model_name='storesaleitem',
            index=models.Index(fields=['sale'], name='store_store_sale_id_ef7f46_idx'),
        ),
        migrations.AddIndex(
            model_name='storestockmovement',
            index=models.Index(fields=['hotel', 'item'], name='store_store_hotel_i_3d9fef_idx'),
        ),
        migrations.AddIndex(
            model_name='storestockmovement',
            index=models.Index(fields=['hotel', 'movement_type'], name='store_store_hotel_i_31b5f8_idx'),
        ),
        migrations.AddIndex(
            model_name='storestockmovement',
            index=models.Index(fields=['hotel', 'created_at'], name='store_store_hotel_i_976913_idx'),
        ),
    ]
