# Generated by Django 6.0.2 on 2026-05-02 08:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('import', 'Import'), ('export', 'Export')], max_length=20)),
                ('app_label', models.CharField(max_length=80)),
                ('model_name', models.CharField(max_length=120)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('success_rows', models.PositiveIntegerField(default=0)),
                ('failed_rows', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial Success')], default='success', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bulk Job',
                'verbose_name_plural': 'Bulk Jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
