# Generated by Django 6.0.2 on 2026-05-04 07:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bulkjob',
            index=models.Index(fields=['action', 'status'], name='bulk_bulkjo_action_7cf033_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkjob',
            index=models.Index(fields=['app_label', 'model_name'], name='bulk_bulkjo_app_lab_8d6166_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkjob',
            index=models.Index(fields=['created_at'], name='bulk_bulkjo_created_31d974_idx'),
        ),
    ]
