# Generated by Django 6.0.2 on 2026-05-02 09:33

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('hotels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('cash_in', 'Cash In'), ('cash_out', 'Cash Out')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('balance_after', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('source_type', models.CharField(db_index=True, max_length=60)),
                ('source_id', models.PositiveBigIntegerField(db_index=True)),
                ('reference', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cash_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='finance.cashaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_movements', to='hotels.hotel')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['hotel', 'direction', 'created_at'], name='finance_cas_hotel_i_7d2966_idx'), models.Index(fields=['hotel', 'source_type', 'source_id'], name='finance_cas_hotel_i_2841d4_idx'), models.Index(fields=['cash_account', 'created_at'], name='finance_cas_cash_ac_96d689_idx')],
                'constraints': [models.UniqueConstraint(fields=('hotel', 'source_type', 'source_id'), name='uniq_cash_movement_source_per_hotel')],
            },
        ),
    ]
