# Generated by Django 6.0.2 on 2026-04-21 09:18

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_expense_expense_number_and_more'),
        ('hotels', '0002_hotelamenity_hotelcategory_hotelchain_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('account_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('revenue', 'Revenue'), ('expense', 'Expense')], db_index=True, max_length=20)),
                ('account_subtype', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('receivable', 'Accounts Receivable'), ('inventory', 'Inventory'), ('prepaid', 'Prepaid Expense'), ('fixed_asset', 'Fixed Asset'), ('accumulated_depreciation', 'Accumulated Depreciation'), ('payable', 'Accounts Payable'), ('tax_payable', 'Tax Payable'), ('salary_payable', 'Salary Payable'), ('customer_deposit', 'Customer Deposit'), ('loan_payable', 'Loan Payable'), ('capital', 'Capital'), ('retained_earnings', 'Retained Earnings'), ('sales', 'Sales Revenue'), ('service_revenue', 'Service Revenue'), ('cogs', 'Cost of Goods Sold'), ('operating_expense', 'Operating Expense'), ('depreciation_expense', 'Depreciation Expense'), ('other', 'Other')], db_index=True, default='other', max_length=40)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'ordering': ['account_code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_number', models.CharField(max_length=50)),
                ('asset_type', models.CharField(choices=[('fixed_asset', 'Fixed Asset'), ('prepaid', 'Prepaid Expense'), ('inventory', 'Inventory'), ('deposit', 'Deposit'), ('other', 'Other')], default='fixed_asset', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('purchase_date', models.DateField(default=django.utils.timezone.localdate)),
                ('purchase_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('current_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('useful_life_months', models.PositiveIntegerField(default=0)),
                ('salvage_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('depreciation_method', models.CharField(default='straight_line', max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disposed', 'Disposed'), ('damaged', 'Damaged'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=20)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'ordering': ['-purchase_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CashAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('mobile_money', 'Mobile Money')], default='cash', max_length=20)),
                ('account_number', models.CharField(blank=True, max_length=100, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cash Account',
                'verbose_name_plural': 'Cash Accounts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_number', models.CharField(max_length=50)),
                ('entry_date', models.DateField(default=django.utils.timezone.localdate)),
                ('reference_type', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('reversed', 'Reversed')], db_index=True, default='draft', max_length=20)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Journal Entry',
                'verbose_name_plural': 'Journal Entries',
                'ordering': ['-entry_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
            ],
            options={
                'verbose_name': 'Journal Line',
                'verbose_name_plural': 'Journal Lines',
            },
        ),
        migrations.CreateModel(
            name='Liability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liability_number', models.CharField(max_length=50)),
                ('liability_type', models.CharField(choices=[('supplier_payable', 'Supplier Payable'), ('tax_payable', 'Tax Payable'), ('salary_payable', 'Salary Payable'), ('customer_deposit', 'Customer Deposit'), ('loan', 'Loan'), ('accrual', 'Accrual'), ('other', 'Other')], default='other', max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('original_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('partial', 'Partial'), ('settled', 'Settled'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Liability',
                'verbose_name_plural': 'Liabilities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('tin_number', models.CharField(blank=True, max_length=50, null=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-expense_date', '-created_at'], 'verbose_name': 'Expense', 'verbose_name_plural': 'Expenses'},
        ),
        migrations.AlterModelOptions(
            name='expenseauditlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='financialperiod',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterModelOptions(
            name='invoiceauditlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-received_at']},
        ),
        migrations.AlterModelOptions(
            name='refund',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='expense',
            name='finance_exp_hotel_i_b73364_idx',
        ),
        migrations.RemoveIndex(
            model_name='expense',
            name='finance_exp_hotel_i_e27adb_idx',
        ),
        migrations.AddField(
            model_name='expense',
            name='balance_due',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='expense',
            name='department',
            field=models.CharField(choices=[('front_office', 'Front Office'), ('housekeeping', 'Housekeeping'), ('restaurant', 'Restaurant'), ('bar', 'Bar'), ('kitchen', 'Kitchen'), ('maintenance', 'Maintenance'), ('laundry', 'Laundry'), ('admin', 'Admin'), ('security', 'Security'), ('store', 'Store'), ('spa', 'Spa / Services'), ('other', 'Other')], db_index=True, default='other', max_length=30),
        ),
        migrations.AddField(
            model_name='expense',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('operational', 'Operational Expense'), ('capital', 'Capital Expenditure'), ('prepaid', 'Prepaid Expense'), ('accrual', 'Accrued Expense')], default='operational', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='expense',
            name='approval_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('partial', 'Partially Paid')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_accounts', to='hotels.hotel'),
        ),
        migrations.AddField(
            model_name='account',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='finance.account'),
        ),
        migrations.AddField(
            model_name='expense',
            name='asset_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='capital_expenses', to='finance.account'),
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.account'),
        ),
        migrations.AddField(
            model_name='expense',
            name='payable_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_payables', to='finance.account'),
        ),
        migrations.AddField(
            model_name='expense',
            name='prepaid_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prepaid_expenses', to='finance.account'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='receivable_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_receivables', to='finance.account'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='revenue_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_revenues', to='finance.account'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_tax_accounts', to='finance.account'),
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_items', to='finance.account'),
        ),
        migrations.AddField(
            model_name='asset',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='depreciation_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='depreciating_assets', to='finance.account'),
        ),
        migrations.AddField(
            model_name='asset',
            name='expense_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_expense_items', to='finance.account'),
        ),
        migrations.AddField(
            model_name='asset',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='hotels.hotel'),
        ),
        migrations.AddField(
            model_name='expense',
            name='linked_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_expenses', to='finance.asset'),
        ),
        migrations.AddField(
            model_name='cashaccount',
            name='gl_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_accounts', to='finance.account'),
        ),
        migrations.AddField(
            model_name='cashaccount',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_accounts', to='hotels.hotel'),
        ),
        migrations.AddField(
            model_name='expense',
            name='cash_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.cashaccount'),
        ),
        migrations.AddField(
            model_name='payment',
            name='cash_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.cashaccount'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_journal_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_journal_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='hotels.hotel'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='finance.account'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='journal_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='liability',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='liability',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liabilities', to='hotels.hotel'),
        ),
        migrations.AddField(
            model_name='liability',
            name='payable_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liability_items', to='finance.account'),
        ),
        migrations.AddField(
            model_name='expense',
            name='linked_liability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_expenses', to='finance.liability'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='hotels.hotel'),
        ),
        migrations.AddField(
            model_name='liability',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liabilities', to='finance.vendor'),
        ),
        migrations.AddField(
            model_name='asset',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='finance.vendor'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='finance.vendor'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['hotel', 'expense_date', 'category'], name='finance_exp_hotel_i_4b15bd_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['hotel', 'expense_date'], name='finance_exp_hotel_i_fc2140_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['hotel', 'department'], name='finance_exp_hotel_i_afd98a_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['hotel', 'account_type'], name='finance_acc_hotel_i_2335ed_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['hotel', 'account_subtype'], name='finance_acc_hotel_i_9f7011_idx'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('hotel', 'account_code'), name='uniq_account_code_per_hotel'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('hotel', 'name'), name='uniq_account_name_per_hotel'),
        ),
        migrations.AddIndex(
            model_name='cashaccount',
            index=models.Index(fields=['hotel', 'account_type'], name='finance_cas_hotel_i_704d6d_idx'),
        ),
        migrations.AddIndex(
            model_name='cashaccount',
            index=models.Index(fields=['hotel', 'is_active'], name='finance_cas_hotel_i_a55a53_idx'),
        ),
        migrations.AddConstraint(
            model_name='cashaccount',
            constraint=models.UniqueConstraint(fields=('hotel', 'name'), name='uniq_cash_account_name_per_hotel'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['hotel', 'entry_date'], name='finance_jou_hotel_i_ddca80_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['hotel', 'status'], name='finance_jou_hotel_i_e1517c_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['hotel', 'reference_type', 'reference_id'], name='finance_jou_hotel_i_a42572_idx'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(fields=('hotel', 'entry_number'), name='uniq_journal_entry_number_per_hotel'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['account'], name='finance_jou_account_85c4ce_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['hotel', 'name'], name='finance_ven_hotel_i_1bb2c3_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['hotel', 'is_active'], name='finance_ven_hotel_i_7b0bdf_idx'),
        ),
        migrations.AddConstraint(
            model_name='vendor',
            constraint=models.UniqueConstraint(fields=('hotel', 'vendor_code'), name='uniq_vendor_code_per_hotel'),
        ),
        migrations.AddConstraint(
            model_name='vendor',
            constraint=models.UniqueConstraint(fields=('hotel', 'name'), name='uniq_vendor_name_per_hotel'),
        ),
        migrations.AddIndex(
            model_name='liability',
            index=models.Index(fields=['hotel', 'liability_type'], name='finance_lia_hotel_i_4a38a0_idx'),
        ),
        migrations.AddIndex(
            model_name='liability',
            index=models.Index(fields=['hotel', 'status'], name='finance_lia_hotel_i_1e9f9b_idx'),
        ),
        migrations.AddIndex(
            model_name='liability',
            index=models.Index(fields=['hotel', 'due_date'], name='finance_lia_hotel_i_546258_idx'),
        ),
        migrations.AddConstraint(
            model_name='liability',
            constraint=models.UniqueConstraint(fields=('hotel', 'liability_number'), name='uniq_liability_number_per_hotel'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['hotel', 'asset_type'], name='finance_ass_hotel_i_4bd0b8_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['hotel', 'status'], name='finance_ass_hotel_i_129a92_idx'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('hotel', 'asset_number'), name='uniq_asset_number_per_hotel'),
        ),
    ]
