from django.urls import path
from . import views

app_name = 'operations'
urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('housekeeping/', views.HousekeepingList.as_view(), name='housekeeping_list'),
    path('housekeeping/new/', views.HousekeepingCreate.as_view(), name='housekeeping_create'),
    path('housekeeping/<int:pk>/', views.HousekeepingDetail.as_view(), name='housekeeping_detail'),
    path('housekeeping/<int:pk>/edit/', views.HousekeepingUpdate.as_view(), name='housekeeping_update'),
    path('maintenance/', views.MaintenanceList.as_view(), name='maintenance_list'),
    path('maintenance/new/', views.MaintenanceCreate.as_view(), name='maintenance_create'),
    path('maintenance/<int:pk>/', views.MaintenanceDetail.as_view(), name='maintenance_detail'),
    path('maintenance/<int:pk>/edit/', views.MaintenanceUpdate.as_view(), name='maintenance_update'),
    path('laundry/', views.LaundryList.as_view(), name='laundry_list'),
    path('laundry/new/', views.LaundryCreate.as_view(), name='laundry_create'),
    path('laundry/<int:pk>/', views.LaundryDetail.as_view(), name='laundry_detail'),
    path('laundry/<int:pk>/edit/', views.LaundryUpdate.as_view(), name='laundry_update'),
    path('lost-found/', views.LostFoundList.as_view(), name='lostfound_list'),
    path('lost-found/new/', views.LostFoundCreate.as_view(), name='lostfound_create'),
    path('lost-found/<int:pk>/', views.LostFoundDetail.as_view(), name='lostfound_detail'),
    path('lost-found/<int:pk>/edit/', views.LostFoundUpdate.as_view(), name='lostfound_update'),
    path('guest-requests/', views.GuestRequestList.as_view(), name='guest_request_list'),
    path('guest-requests/new/', views.GuestRequestCreate.as_view(), name='guest_request_create'),
    path('guest-requests/<int:pk>/', views.GuestRequestDetail.as_view(), name='guest_request_detail'),
    path('guest-requests/<int:pk>/edit/', views.GuestRequestUpdate.as_view(), name='guest_request_update'),
    path('night-audit/', views.NightAuditList.as_view(), name='night_audit_list'),
    path('night-audit/new/', views.NightAuditCreate.as_view(), name='night_audit_create'),
    path('night-audit/<int:pk>/', views.NightAuditDetail.as_view(), name='night_audit_detail'),
    path('night-audit/<int:pk>/edit/', views.NightAuditUpdate.as_view(), name='night_audit_update'),
    path('channel-rates/', views.ChannelRateList.as_view(), name='channel_rate_list'),
    path('channel-rates/new/', views.ChannelRateCreate.as_view(), name='channel_rate_create'),
    path('channel-rates/<int:pk>/', views.ChannelRateDetail.as_view(), name='channel_rate_detail'),
    path('channel-rates/<int:pk>/edit/', views.ChannelRateUpdate.as_view(), name='channel_rate_update'),
    path('kitchen-tickets/', views.KitchenTicketList.as_view(), name='kitchen_ticket_list'),
    path('kitchen-tickets/new/', views.KitchenTicketCreate.as_view(), name='kitchen_ticket_create'),
    path('kitchen-tickets/<int:pk>/', views.KitchenTicketDetail.as_view(), name='kitchen_ticket_detail'),
    path('kitchen-tickets/<int:pk>/edit/', views.KitchenTicketUpdate.as_view(), name='kitchen_ticket_update'),
]
