# Generated by Django 6.0.2 on 2026-02-26 07:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('website', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_number', models.CharField(blank=True, max_length=50, null=True)),
                ('business_registration', models.CharField(blank=True, max_length=50, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='hotel_logos/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='hotel_favicons/')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotels',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='hotels_hote_name_c9f1ff_idx'), models.Index(fields=['slug'], name='hotels_hote_slug_ae692c_idx'), models.Index(fields=['is_active'], name='hotels_hote_is_acti_64ad6f_idx')],
            },
        ),
        migrations.CreateModel(
            name='HotelSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_description', models.TextField(blank=True, null=True)),
                ('short_description', models.CharField(blank=True, max_length=500, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=30, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='hotel_logos/')),
                ('logo_light', models.ImageField(blank=True, null=True, upload_to='hotel_logos/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='hotel_favicons/')),
                ('brand_color', models.CharField(blank=True, help_text='Hex color code', max_length=7, null=True)),
                ('instagram', models.CharField(blank=True, max_length=3060, null=True)),
                ('twitter', models.CharField(blank=True, max_length=3060, null=True)),
                ('facebook', models.CharField(blank=True, max_length=3060, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=3060, null=True)),
                ('youtube', models.CharField(blank=True, max_length=3060, null=True)),
                ('check_in_time', models.TimeField(default='14:00')),
                ('check_out_time', models.TimeField(default='11:00')),
                ('reception_open_time', models.TimeField(default='00:00')),
                ('reception_close_time', models.TimeField(default='23:59')),
                ('cancellation_policy', models.TextField(blank=True, null=True)),
                ('payment_policy', models.TextField(blank=True, null=True)),
                ('house_rules', models.TextField(blank=True, null=True)),
                ('default_tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax_number', models.CharField(blank=True, max_length=50, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('currency_symbol', models.CharField(default='$', max_length=5)),
                ('google_maps_api_key', models.CharField(blank=True, max_length=3060, null=True)),
                ('payment_gateway_key', models.CharField(blank=True, max_length=3060, null=True)),
                ('payment_gateway_secret', models.CharField(blank=True, max_length=3060, null=True)),
                ('sms_api_key', models.CharField(blank=True, max_length=3060, null=True)),
                ('email_api_key', models.CharField(blank=True, max_length=3060, null=True)),
                ('enable_online_booking', models.BooleanField(default=True)),
                ('enable_restaurant_ordering', models.BooleanField(default=True)),
                ('enable_loyalty_program', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='hotels.hotel')),
            ],
            options={
                'verbose_name': 'Hotel Setting',
                'verbose_name_plural': 'Hotel Settings',
            },
        ),
    ]
