# Generated by ChatGPT for hotel currency setup

from django.db import migrations, models


def seed_hotel_currencies(apps, schema_editor):
    Hotel = apps.get_model("hotels", "Hotel")
    HotelSetting = apps.get_model("hotels", "HotelSetting")
    for hotel in Hotel.objects.all():
        setting = HotelSetting.objects.filter(hotel=hotel).first()
        currency = "UGX"
        symbol = "UGX"
        if setting:
            currency = (setting.currency or "UGX").upper()[:3]
            symbol = setting.currency_symbol or currency
        hotel.default_currency = currency
        hotel.default_currency_symbol = symbol
        hotel.supported_currencies = [currency]
        hotel.save(update_fields=["default_currency", "default_currency_symbol", "supported_currencies"])


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="default_currency",
            field=models.CharField(default="UGX", max_length=3),
        ),
        migrations.AddField(
            model_name="hotel",
            name="default_currency_symbol",
            field=models.CharField(default="UGX", max_length=8),
        ),
        migrations.AddField(
            model_name="hotel",
            name="supported_currencies",
            field=models.JSONField(blank=True, default=list, help_text="List of supported ISO currency codes, e.g. UGX, USD, EUR"),
        ),
        migrations.RunPython(seed_hotel_currencies, migrations.RunPython.noop),
    ]
