# Generated by Django 6.0.2 on 2026-04-17 20:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('category', models.CharField(choices=[('general', 'General'), ('room', 'Room'), ('bathroom', 'Bathroom'), ('food_drink', 'Food & Drink'), ('internet', 'Internet'), ('entertainment', 'Entertainment'), ('services', 'Services'), ('business', 'Business'), ('safety', 'Safety & Security'), ('accessibility', 'Accessibility'), ('parking', 'Parking & Transport'), ('pool_spa', 'Pool & Spa'), ('fitness', 'Fitness'), ('family', 'Family Friendly'), ('outdoor', 'Outdoor')], default='general', max_length=50)),
                ('icon', models.CharField(blank=True, help_text='Font awesome icon class', max_length=50, null=True)),
                ('is_paid', models.BooleanField(default=False, help_text='Whether this amenity requires additional payment')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Amenities',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HotelCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('star_rating_min', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('star_rating_max', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('icon', models.CharField(blank=True, help_text='Font awesome icon class', max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Hotel Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HotelChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='hotel_chains/logos/')),
                ('website', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('description', models.TextField(blank=True, null=True)),
                ('headquarters_address', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hotel Chain',
                'verbose_name_plural': 'Hotel Chains',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HotelContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(choices=[('general_manager', 'General Manager'), ('reservation_manager', 'Reservation Manager'), ('front_office_manager', 'Front Office Manager'), ('sales_manager', 'Sales Manager'), ('owner', 'Owner'), ('other', 'Other')], max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('phone_alt', models.CharField(blank=True, max_length=30, null=True)),
                ('is_primary', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Person',
                'verbose_name_plural': 'Contact Persons',
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HotelDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('registration', 'Business Registration'), ('tax_certificate', 'Tax Certificate'), ('license', 'Operating License'), ('insurance', 'Insurance Certificate'), ('contract', 'Contract'), ('identification', 'Identification'), ('other', 'Other')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='hotel_documents/%Y/%m/%d/')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hotel Document',
                'verbose_name_plural': 'Hotel Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hotel_gallery/%Y/%m/%d/')),
                ('category', models.CharField(choices=[('exterior', 'Exterior'), ('interior', 'Interior'), ('lobby', 'Lobby'), ('reception', 'Reception'), ('room', 'Room'), ('suite', 'Suite'), ('bathroom', 'Bathroom'), ('restaurant', 'Restaurant'), ('bar', 'Bar/Lounge'), ('pool', 'Pool'), ('spa', 'Spa'), ('gym', 'Gym/Fitness'), ('conference', 'Conference/Banquet'), ('event', 'Event Space'), ('parking', 'Parking'), ('view', 'View'), ('food', 'Food & Dining'), ('other', 'Other')], default='other', max_length=50)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('alt_text', models.CharField(blank=True, help_text='SEO alt text', max_length=255, null=True)),
                ('caption', models.CharField(blank=True, max_length=500, null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('is_primary', models.BooleanField(default=False, help_text='Set as primary image for this category')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured in gallery')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_size', models.IntegerField(blank=True, help_text='File size in bytes', null=True)),
            ],
            options={
                'verbose_name': 'Hotel Image',
                'verbose_name_plural': 'Hotel Images',
                'ordering': ['order', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='HotelReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=255)),
                ('guest_email', models.EmailField(max_length=254)),
                ('overall_rating', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('cleanliness_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comfort_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('location_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('staff_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('facilities_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('value_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(max_length=255)),
                ('review_text', models.TextField()),
                ('pros', models.TextField(blank=True, help_text='What did you like?', null=True)),
                ('cons', models.TextField(blank=True, help_text='What could be improved?', null=True)),
                ('stay_date_from', models.DateField()),
                ('stay_date_to', models.DateField()),
                ('room_number', models.CharField(blank=True, max_length=50, null=True)),
                ('is_verified_stay', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False, help_text='Approved for public display')),
                ('hotel_response', models.TextField(blank=True, null=True)),
                ('hotel_response_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hotel Review',
                'verbose_name_plural': 'Hotel Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='hotel',
            name='brand_color_primary',
            field=models.CharField(blank=True, help_text='Primary brand color (hex)', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='brand_color_secondary',
            field=models.CharField(blank=True, help_text='Secondary brand color (hex)', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='cancellation_policy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='check_in_time',
            field=models.TimeField(default='14:00'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='check_out_time',
            field=models.TimeField(default='11:00'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='child_policy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='hotel_covers/'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_hotels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hotel',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed hotel description', null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='hotel',
            name='house_rules',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='instagram_url',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='hotel',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured on homepage'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Verified hotel'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Latitude for map location', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='hotel',
            name='logo_light',
            field=models.ImageField(blank=True, null=True, upload_to='hotel_logos/'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Longitude for map location', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO meta description', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='SEO keywords', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='number_of_employees',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='payment_policy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='pet_policy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='phone_alt',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Alternative Phone'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='reception_close_time',
            field=models.TimeField(default='23:59'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='reception_open_time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='short_description',
            field=models.CharField(blank=True, help_text='Brief description for listings', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='star_rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Hotel star rating (0-5)', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='hotel',
            name='total_floors',
            field=models.IntegerField(default=1, help_text='Number of floors'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='total_rooms',
            field=models.IntegerField(default=0, help_text='Total number of rooms'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='tripadvisor_url',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='hotel',
            name='twitter_url',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='hotel',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='year_established',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='youtube_url',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='hotelsetting',
            name='send_booking_confirmation_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hotelsetting',
            name='send_booking_confirmation_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotelsetting',
            name='send_checkin_reminder',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hotelsetting',
            name='send_checkout_reminder',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='country',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='state',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='HotelAmenityMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('additional_info', models.CharField(blank=True, max_length=255, null=True)),
                ('charge_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_mappings', to='hotels.hotelamenity')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenity_mappings', to='hotels.hotel')),
            ],
            options={
                'verbose_name': 'Hotel Amenity',
                'verbose_name_plural': 'Hotel Amenities',
            },
        ),
        migrations.CreateModel(
            name='HotelBankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255)),
                ('account_holder_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=100)),
                ('routing_number', models.CharField(blank=True, max_length=100, null=True)),
                ('swift_code', models.CharField(blank=True, max_length=20, null=True)),
                ('iban', models.CharField(blank=True, max_length=50, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='hotels.hotel')),
            ],
            options={
                'verbose_name': 'Bank Detail',
                'verbose_name_plural': 'Bank Details',
            },
        ),
        migrations.AddField(
            model_name='hotel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotels', to='hotels.hotelcategory'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_chain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotels', to='hotels.hotelchain'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['is_published'], name='hotels_hote_is_publ_d374c6_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['city', 'country'], name='hotels_hote_city_a01868_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['star_rating'], name='hotels_hote_star_ra_e9d0d2_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['latitude', 'longitude'], name='hotels_hote_latitud_bb0edd_idx'),
        ),
        migrations.AddField(
            model_name='hotelcontactperson',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_persons', to='hotels.hotel'),
        ),
        migrations.AddField(
            model_name='hoteldocument',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='hotels.hotel'),
        ),
        migrations.AddField(
            model_name='hoteldocument',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hotelimage',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hotels.hotel'),
        ),
        migrations.AddField(
            model_name='hotelreview',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='hotels.hotel'),
        ),
        migrations.AddField(
            model_name='hotelreview',
            name='responded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='hotelamenitymapping',
            unique_together={('hotel', 'amenity')},
        ),
        migrations.AddIndex(
            model_name='hotelimage',
            index=models.Index(fields=['hotel', 'category'], name='hotels_hote_hotel_i_55c92b_idx'),
        ),
        migrations.AddIndex(
            model_name='hotelimage',
            index=models.Index(fields=['is_primary'], name='hotels_hote_is_prim_5a0e0f_idx'),
        ),
        migrations.AddIndex(
            model_name='hotelimage',
            index=models.Index(fields=['is_featured'], name='hotels_hote_is_feat_788767_idx'),
        ),
        migrations.AddIndex(
            model_name='hotelreview',
            index=models.Index(fields=['hotel', 'is_approved'], name='hotels_hote_hotel_i_4be9e2_idx'),
        ),
        migrations.AddIndex(
            model_name='hotelreview',
            index=models.Index(fields=['overall_rating'], name='hotels_hote_overall_20d72c_idx'),
        ),
        migrations.AddIndex(
            model_name='hotelreview',
            index=models.Index(fields=['-created_at'], name='hotels_hote_created_e568ff_idx'),
        ),
    ]
