# Generated by Django 6.0.2 on 2026-05-20 14:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_hotel_currencies'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=255)),
                ('guest_email', models.EmailField(max_length=254)),
                ('place_visited', models.CharField(help_text='e.g. Mount Rwenzori, Queen Elizabeth National Park', max_length=255)),
                ('activity', models.CharField(help_text='e.g. Mountain Climbing, Wildlife Safari', max_length=255)),
                ('rating', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('experience_text', models.TextField(help_text='Describe your experience and activities')),
                ('is_approved', models.BooleanField(default=True, help_text='Approved for public display')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='hotels.hotel')),
            ],
            options={
                'verbose_name': 'Hotel Experience',
                'verbose_name_plural': 'Hotel Experiences',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HotelExperienceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='experiences/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hotels.hotelexperience')),
            ],
            options={
                'verbose_name': 'Hotel Experience Image',
                'verbose_name_plural': 'Hotel Experience Images',
                'ordering': ['created_at'],
            },
        ),
    ]
