# Generated by Django 6.0.2 on 2026-03-09 15:12

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0003_alter_additionalcharge_options_alter_booking_options_and_more'),
        ('hotels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=60, null=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('attendants', models.PositiveIntegerField(default=1)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField(blank=True, null=True)),
                ('pricing_mode', models.CharField(blank=True, choices=[('fixed', 'Fixed'), ('per_person', 'Per Person'), ('per_hour', 'Per Hour'), ('per_day', 'Per Day'), ('per_session', 'Per Session'), ('custom', 'Custom')], max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('deposit_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('post_to_room', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('reserved', 'Reserved'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], db_index=True, default='reserved', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('paid', 'Paid'), ('room_posted', 'Posted to Room'), ('waived', 'Waived')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_service_bookings', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_entries', to='bookings.booking')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_bookings', to='hotels.hotel')),
            ],
            options={
                'ordering': ['-scheduled_start', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_checkins', to=settings.AUTH_USER_MODEL)),
                ('checked_out_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_checkouts', to=settings.AUTH_USER_MODEL)),
                ('service_booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='services.servicebooking')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceBookingExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('service_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='services.servicebooking')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_categories', to='hotels.hotel')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('mobile', 'Mobile Money'), ('card', 'Card'), ('bank', 'Bank Transfer'), ('room_post', 'Room Post'), ('other', 'Other')], default='cash', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=120, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('service_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='services.servicebooking')),
            ],
            options={
                'ordering': ['-paid_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_resources', to='hotels.hotel')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='services.serviceresource'),
        ),
        migrations.CreateModel(
            name='ServiceUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, max_length=30, null=True)),
                ('service_type', models.CharField(choices=[('facility', 'Facility'), ('package', 'Package'), ('venue', 'Venue'), ('activity', 'Activity'), ('transport', 'Transport'), ('other', 'Other')], default='facility', max_length=20)),
                ('pricing_mode', models.CharField(choices=[('fixed', 'Fixed'), ('per_person', 'Per Person'), ('per_hour', 'Per Hour'), ('per_day', 'Per Day'), ('per_session', 'Per Session'), ('custom', 'Custom')], default='fixed', max_length=20)),
                ('base_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('default_duration_minutes', models.PositiveIntegerField(default=60)),
                ('max_capacity', models.PositiveIntegerField(default=1)),
                ('requires_schedule', models.BooleanField(default=True)),
                ('allows_walk_in', models.BooleanField(default=True)),
                ('allow_post_to_room', models.BooleanField(default=True)),
                ('requires_attendant', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='services.servicecategory')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_units', to='hotels.hotel')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='serviceresource',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='services.serviceunit'),
        ),
        migrations.CreateModel(
            name='ServicePackageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=150)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('unit', models.CharField(default='unit', max_length=30)),
                ('extra_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_optional', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_items', to='services.serviceunit')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='services.serviceunit'),
        ),
        migrations.AddIndex(
            model_name='servicecategory',
            index=models.Index(fields=['hotel', 'is_active'], name='services_se_hotel_i_93d320_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecategory',
            index=models.Index(fields=['hotel', 'sort_order'], name='services_se_hotel_i_cd009c_idx'),
        ),
        migrations.AddConstraint(
            model_name='servicecategory',
            constraint=models.UniqueConstraint(fields=('hotel', 'name'), name='uniq_service_category_per_hotel'),
        ),
        migrations.AddIndex(
            model_name='servicepayment',
            index=models.Index(fields=['paid_at'], name='services_se_paid_at_95403a_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceunit',
            index=models.Index(fields=['hotel', 'category'], name='services_se_hotel_i_cdd5fb_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceunit',
            index=models.Index(fields=['hotel', 'service_type'], name='services_se_hotel_i_cc51b6_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceunit',
            index=models.Index(fields=['hotel', 'is_active'], name='services_se_hotel_i_3194a3_idx'),
        ),
        migrations.AddConstraint(
            model_name='serviceunit',
            constraint=models.UniqueConstraint(fields=('hotel', 'name'), name='uniq_service_unit_name_per_hotel'),
        ),
        migrations.AddIndex(
            model_name='serviceresource',
            index=models.Index(fields=['hotel', 'service'], name='services_se_hotel_i_2162e4_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceresource',
            index=models.Index(fields=['hotel', 'is_active'], name='services_se_hotel_i_4de7a6_idx'),
        ),
        migrations.AddConstraint(
            model_name='serviceresource',
            constraint=models.UniqueConstraint(fields=('service', 'name'), name='uniq_service_resource_name'),
        ),
        migrations.AddIndex(
            model_name='servicebooking',
            index=models.Index(fields=['hotel', 'service'], name='services_se_hotel_i_8adbdd_idx'),
        ),
        migrations.AddIndex(
            model_name='servicebooking',
            index=models.Index(fields=['hotel', 'status'], name='services_se_hotel_i_26bbcd_idx'),
        ),
        migrations.AddIndex(
            model_name='servicebooking',
            index=models.Index(fields=['hotel', 'payment_status'], name='services_se_hotel_i_0bfd43_idx'),
        ),
        migrations.AddIndex(
            model_name='servicebooking',
            index=models.Index(fields=['hotel', 'scheduled_start'], name='services_se_hotel_i_cb0ea4_idx'),
        ),
        migrations.AddIndex(
            model_name='servicebooking',
            index=models.Index(fields=['hotel', 'reference'], name='services_se_hotel_i_6c1faf_idx'),
        ),
    ]
