# Generated by Django 6.0.2 on 2026-02-26 07:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('general_manager', 'General Manager'), ('operations_manager', 'Operations Manager'), ('front_desk_manager', 'Front Desk Manager'), ('front_desk', 'Front Desk Staff'), ('housekeeping_manager', 'Housekeeping Manager'), ('housekeeper', 'Housekeeper'), ('restaurant_manager', 'Restaurant Manager'), ('server', 'Server'), ('chef', 'Chef'), ('accountant', 'Accountant'), ('maintenance', 'Maintenance'), ('viewer', 'Viewer Only')], default='viewer', max_length=30)),
                ('permission_level', models.CharField(choices=[('full', 'Full Access'), ('read_write', 'Read & Write'), ('read_only', 'Read Only'), ('restricted', 'Restricted')], default='read_write', max_length=20)),
                ('can_access_front_desk', models.BooleanField(default=False)),
                ('can_access_housekeeping', models.BooleanField(default=False)),
                ('can_access_restaurant', models.BooleanField(default=False)),
                ('can_access_finance', models.BooleanField(default=False)),
                ('can_access_maintenance', models.BooleanField(default=False)),
                ('can_access_reports', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_primary_contact', models.BooleanField(default=False, help_text='Primary contact for this hotel')),
                ('invitation_sent_at', models.DateTimeField(blank=True, null=True)),
                ('invitation_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='hotels.hotel')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_members', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hotel Member',
                'verbose_name_plural': 'Hotel Members',
                'ordering': ['hotel__name', 'role', 'user__email'],
                'indexes': [models.Index(fields=['hotel', 'role', 'is_active'], name='accounts_ho_hotel_i_f18fd1_idx'), models.Index(fields=['user', 'is_active'], name='accounts_ho_user_id_f88681_idx'), models.Index(fields=['hotel', 'last_accessed'], name='accounts_ho_hotel_i_44adef_idx')],
                'constraints': [models.UniqueConstraint(fields=('hotel', 'user'), name='uniq_user_per_hotel')],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', message='Enter a valid phone number.')])),
                ('alternative_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('es', 'Spanish'), ('ar', 'Arabic'), ('zh', 'Chinese'), ('ru', 'Russian')], default='en', max_length=10)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('notification_email', models.BooleanField(default=True)),
                ('notification_sms', models.BooleanField(default=False)),
                ('notification_push', models.BooleanField(default=True)),
                ('last_active', models.DateTimeField(blank=True, null=True)),
                ('last_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'indexes': [models.Index(fields=['user', 'employee_id'], name='accounts_pr_user_id_0a9af7_idx'), models.Index(fields=['phone'], name='accounts_pr_phone_a8479a_idx'), models.Index(fields=['last_active'], name='accounts_pr_last_ac_aa6f97_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('export', 'Export'), ('print', 'Print')], max_length=20)),
                ('content_type', models.CharField(blank=True, max_length=100, null=True)),
                ('object_id', models.CharField(blank=True, max_length=50, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_activities', to='hotels.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Activity Log',
                'verbose_name_plural': 'User Activity Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='accounts_us_user_id_3c3f09_idx'), models.Index(fields=['hotel', '-created_at'], name='accounts_us_hotel_i_13d1b8_idx'), models.Index(fields=['action', 'created_at'], name='accounts_us_action_f244c7_idx')],
            },
        ),
    ]
