# Generated by Django 6.0.2 on 2026-04-18 06:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('hotels', '0002_hotelamenity_hotelcategory_hotelchain_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user__last_name', 'user__first_name'], 'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.RenameIndex(
            model_name='hotelmember',
            new_name='hotel_role_active_idx',
            old_name='accounts_ho_hotel_i_f18fd1_idx',
        ),
        migrations.RenameIndex(
            model_name='hotelmember',
            new_name='user_active_idx',
            old_name='accounts_ho_user_id_f88681_idx',
        ),
        migrations.RenameIndex(
            model_name='hotelmember',
            new_name='hotel_last_access_idx',
            old_name='accounts_ho_hotel_i_44adef_idx',
        ),
        migrations.RenameIndex(
            model_name='profile',
            new_name='profile_user_emp_idx',
            old_name='accounts_pr_user_id_0a9af7_idx',
        ),
        migrations.RenameIndex(
            model_name='profile',
            new_name='profile_phone_idx',
            old_name='accounts_pr_phone_a8479a_idx',
        ),
        migrations.RenameIndex(
            model_name='profile',
            new_name='profile_active_idx',
            old_name='accounts_pr_last_ac_aa6f97_idx',
        ),
        migrations.RenameIndex(
            model_name='useractivitylog',
            new_name='user_activity_idx',
            old_name='accounts_us_user_id_3c3f09_idx',
        ),
        migrations.RenameIndex(
            model_name='useractivitylog',
            new_name='hotel_activity_idx',
            old_name='accounts_us_hotel_i_13d1b8_idx',
        ),
        migrations.RenameIndex(
            model_name='useractivitylog',
            new_name='action_date_idx',
            old_name='accounts_us_action_f244c7_idx',
        ),
        migrations.AddField(
            model_name='hotelmember',
            name='department_access',
            field=models.JSONField(blank=True, default=dict, help_text='JSON field storing department-specific permissions'),
        ),
        migrations.AddField(
            model_name='hotelmember',
            name='invitation_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelmember',
            name='terminated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelmember',
            name='terminated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminated_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hotelmember',
            name='termination_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='profile_avatars/%Y/%m/%d/', verbose_name='Profile Picture'),
        ),
        migrations.AddField(
            model_name='profile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_login_device',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='notification_digest',
            field=models.BooleanField(default=True, verbose_name='Daily Digest'),
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='changes',
            field=models.JSONField(blank=True, default=dict, help_text='Stores before/after state for updates'),
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='duration_ms',
            field=models.PositiveIntegerField(blank=True, help_text='Request duration in milliseconds', null=True),
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='request_method',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='request_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='response_status',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotelmember',
            name='invitation_accepted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotelmember',
            name='invitation_sent_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotelmember',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='hotelmember',
            name='is_primary_contact',
            field=models.BooleanField(db_index=True, default=False, help_text='Primary contact for this hotel'),
        ),
        migrations.AlterField(
            model_name='hotelmember',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='hotelmember',
            name='last_accessed',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotelmember',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('general_manager', 'General Manager'), ('operations_manager', 'Operations Manager'), ('front_desk_manager', 'Front Desk Manager'), ('front_desk', 'Front Desk Staff'), ('housekeeping_manager', 'Housekeeping Manager'), ('housekeeper', 'Housekeeper'), ('restaurant_manager', 'Restaurant Manager'), ('server', 'Server'), ('chef', 'Chef'), ('accountant', 'Accountant'), ('maintenance', 'Maintenance'), ('viewer', 'Viewer Only')], db_index=True, default='viewer', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='alternative_phone',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', message='Enter a valid phone number.')], verbose_name='Alternative Phone'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, db_index=True, default='US', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='employee_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='Employee ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Job Title'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('es', 'Spanish'), ('ar', 'Arabic'), ('zh', 'Chinese'), ('ru', 'Russian'), ('de', 'German'), ('it', 'Italian'), ('pt', 'Portuguese'), ('ja', 'Japanese'), ('ko', 'Korean')], db_index=True, default='en', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_active',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='notification_email',
            field=models.BooleanField(default=True, verbose_name='Email Notifications'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='notification_push',
            field=models.BooleanField(default=True, verbose_name='Push Notifications'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='notification_sms',
            field=models.BooleanField(default=False, verbose_name='SMS Notifications'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (9-15 digits, optional + prefix).', regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='timezone',
            field=models.CharField(default='UTC', help_text="User's preferred timezone for date/time display", max_length=50),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Login Failed'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('export', 'Export'), ('print', 'Print'), ('download', 'Download'), ('upload', 'Upload'), ('share', 'Share'), ('permission_change', 'Permission Change')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='content_type',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='object_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='hotelmember',
            index=models.Index(fields=['role', 'permission_level'], name='role_permission_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['department', 'job_title'], name='profile_dept_job_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['city', 'country'], name='profile_location_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['is_active', '-created_at'], name='profile_active_created_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['content_type', 'object_id'], name='object_tracking_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['ip_address', 'created_at'], name='ip_date_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['-created_at'], name='recent_activity_idx'),
        ),
        migrations.AddConstraint(
            model_name='hotelmember',
            constraint=models.CheckConstraint(condition=models.Q(('invitation_accepted_at__isnull', True), ('invitation_accepted_at__gte', models.F('invitation_sent_at')), _connector='OR'), name='invitation_accepted_after_sent'),
        ),
    ]
