# Generated by Django 6.0.2 on 2026-04-18 06:14

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_options_and_more'),
        ('hotels', '0002_hotelamenity_hotelcategory_hotelchain_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelmember',
            name='badges',
            field=models.JSONField(blank=True, default=list, help_text='List of badges earned'),
        ),
        migrations.AddField(
            model_name='hotelmember',
            name='can_manage_bookings',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotelmember',
            name='can_manage_inventory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotelmember',
            name='can_manage_reports',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotelmember',
            name='can_manage_rooms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotelmember',
            name='can_manage_settings',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotelmember',
            name='can_manage_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotelmember',
            name='can_view_financials',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotelmember',
            name='certifications',
            field=models.JSONField(blank=True, default=list, help_text='List of certifications with expiry dates'),
        ),
        migrations.AddField(
            model_name='hotelmember',
            name='contract_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelmember',
            name='contract_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelmember',
            name='currency',
            field=models.CharField(blank=True, default='USD', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='hotelmember',
            name='default_shift_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelmember',
            name='default_shift_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelmember',
            name='eligible_for_rehire',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hotelmember',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hotelmember',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='hotelmember',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotelmember',
            name='employee_code',
            field=models.CharField(blank=True, db_index=True, help_text='Unique employee identifier within the system', max_length=50, null=True, unique=True, verbose_name='Employee Code'),
        ),
        migrations.AddField(
            model_name='hotelmember',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('seasonal', 'Seasonal'), ('intern', 'Intern'), ('temporary', 'Temporary'), ('on_call', 'On Call')], db_index=True, default='full_time', max_length=20),
        ),
        migrations.AddField(
            model_name='hotelmember',
            name='hire_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelmember',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Hourly Rate'),
        ),
        migrations.AddField(
            model_name='hotelmember',
            name='is_on_leave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotelmember',
            name='languages_spoken',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='hotelmember',
            name='last_review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelmember',
            name='last_training_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelmember',
            name='leave_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelmember',
            name='leave_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelmember',
            name='leave_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelmember',
            name='max_weekly_hours',
            field=models.PositiveSmallIntegerField(blank=True, default=40, null=True),
        ),
        migrations.AddField(
            model_name='hotelmember',
            name='next_review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelmember',
            name='next_training_due',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelmember',
            name='overtime_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotelmember',
            name='performance_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelmember',
            name='performance_rating',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Performance rating from 0.00 to 5.00', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='hotelmember',
            name='probation_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelmember',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Hotel-specific profile picture (overrides global profile picture)', max_length=500, null=True, upload_to='hotel_members/%Y/%m/%d/', verbose_name='Profile Picture'),
        ),
        migrations.AddField(
            model_name='hotelmember',
            name='profile_picture_thumbnail',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='hotel_members/thumbnails/%Y/%m/%d/', verbose_name='Profile Picture Thumbnail'),
        ),
        migrations.AddField(
            model_name='hotelmember',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Annual Salary'),
        ),
        migrations.AddField(
            model_name='hotelmember',
            name='shift_preference',
            field=models.CharField(choices=[('morning', 'Morning (6 AM - 2 PM)'), ('afternoon', 'Afternoon (2 PM - 10 PM)'), ('night', 'Night (10 PM - 6 AM)'), ('rotating', 'Rotating'), ('flexible', 'Flexible')], default='flexible', max_length=20),
        ),
        migrations.AddField(
            model_name='hotelmember',
            name='special_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelmember',
            name='training_completed',
            field=models.JSONField(blank=True, default=list, help_text='List of completed training modules'),
        ),
        migrations.AddField(
            model_name='hotelmember',
            name='work_email',
            field=models.EmailField(blank=True, help_text='Hotel-specific email address', max_length=254, null=True, verbose_name='Work Email'),
        ),
        migrations.AddField(
            model_name='hotelmember',
            name='work_phone',
            field=models.CharField(blank=True, help_text='Hotel-specific work phone number', max_length=30, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', message='Enter a valid phone number.')], verbose_name='Work Phone'),
        ),
        migrations.AddField(
            model_name='hotelmember',
            name='years_of_service_awards',
            field=models.JSONField(blank=True, default=list, help_text='Years of service awards received'),
        ),
        migrations.AlterField(
            model_name='hotelmember',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('general_manager', 'General Manager'), ('operations_manager', 'Operations Manager'), ('front_desk_manager', 'Front Desk Manager'), ('front_desk', 'Front Desk Staff'), ('housekeeping_manager', 'Housekeeping Manager'), ('housekeeper', 'Housekeeper'), ('restaurant_manager', 'Restaurant Manager'), ('server', 'Server'), ('chef', 'Chef'), ('accountant', 'Accountant'), ('maintenance', 'Maintenance'), ('security', 'Security Staff'), ('viewer', 'Viewer Only')], db_index=True, default='viewer', max_length=30),
        ),
        migrations.AddIndex(
            model_name='hotelmember',
            index=models.Index(fields=['employee_code'], name='employee_code_idx'),
        ),
        migrations.AddIndex(
            model_name='hotelmember',
            index=models.Index(fields=['hire_date', 'is_active'], name='hire_date_active_idx'),
        ),
        migrations.AddIndex(
            model_name='hotelmember',
            index=models.Index(fields=['hotel', 'employment_type'], name='employment_type_idx'),
        ),
        migrations.AddIndex(
            model_name='hotelmember',
            index=models.Index(fields=['shift_preference'], name='shift_preference_idx'),
        ),
        migrations.AddIndex(
            model_name='hotelmember',
            index=models.Index(fields=['performance_rating'], name='performance_rating_idx'),
        ),
        migrations.AddIndex(
            model_name='hotelmember',
            index=models.Index(fields=['next_training_due'], name='training_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='hotelmember',
            constraint=models.UniqueConstraint(condition=models.Q(('employee_code__isnull', False)), fields=('employee_code',), name='uniq_employee_code'),
        ),
        migrations.AddConstraint(
            model_name='hotelmember',
            constraint=models.CheckConstraint(condition=models.Q(('contract_end_date__isnull', True), ('contract_end_date__gte', models.F('contract_start_date')), _connector='OR'), name='contract_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='hotelmember',
            constraint=models.CheckConstraint(condition=models.Q(('leave_end_date__isnull', True), ('leave_end_date__gte', models.F('leave_start_date')), _connector='OR'), name='leave_end_after_start'),
        ),
    ]
