# Generated by Django 6.0.2 on 2026-05-02 08:47

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('hotels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiningArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Main Hall, Terrace, VIP Room', max_length=120)),
                ('description', models.TextField(blank=True, help_text='Optional description of the area', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dining_areas', to='hotels.hotel')),
            ],
            options={
                'ordering': ['hotel__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Appetizers, Main Course, Desserts, Beverages', max_length=120)),
                ('description', models.TextField(blank=True, help_text='Optional category description', null=True)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_categories', to='hotels.hotel')),
            ],
            options={
                'ordering': ['hotel__name', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the dish/beverage', max_length=160)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the item', null=True)),
                ('ingredients', models.TextField(blank=True, help_text='List of main ingredients', null=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Selling price to customers', max_digits=12)),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cost price for profit calculation', max_digits=12)),
                ('track_stock', models.BooleanField(default=False, help_text='Enable automatic stock tracking')),
                ('stock_qty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current stock quantity', max_digits=12)),
                ('reorder_level', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Stock level that triggers reorder alert', max_digits=12)),
                ('is_vegetarian', models.BooleanField(default=False, help_text='Suitable for vegetarians')),
                ('is_vegan', models.BooleanField(default=False, help_text='Suitable for vegans')),
                ('is_gluten_free', models.BooleanField(default=False, help_text='Gluten-free option')),
                ('is_spicy', models.BooleanField(default=False, help_text='Contains spicy ingredients')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured on the menu')),
                ('is_recommended', models.BooleanField(default=False, help_text="Chef's recommendation")),
                ('is_active', models.BooleanField(default=True, help_text='Available for ordering')),
                ('preparation_time', models.PositiveIntegerField(default=15, help_text='Estimated preparation time in minutes')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='restaurant.menucategory')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='hotels.hotel')),
            ],
            options={
                'ordering': ['hotel__name', 'category__sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, help_text='Customer name for walk-ins', max_length=255, null=True)),
                ('customer_phone', models.CharField(blank=True, help_text='Customer contact number', max_length=30, null=True)),
                ('customer_email', models.EmailField(blank=True, help_text='Customer email for receipts', max_length=254, null=True)),
                ('room_charge', models.BooleanField(default=False, help_text="Charge to guest's room")),
                ('status', models.CharField(choices=[('open', 'Open'), ('kitchen', 'In Kitchen'), ('served', 'Served'), ('billed', 'Billed'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=20)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount amount', max_digits=12)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount percentage', max_digits=5)),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax amount', max_digits=12)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax percentage', max_digits=5)),
                ('service_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Service charge amount', max_digits=12)),
                ('order_number', models.CharField(blank=True, max_length=60, null=True, unique=True)),
                ('special_instructions', models.TextField(blank=True, help_text='Special requests or instructions', null=True)),
                ('kitchen_notes', models.TextField(blank=True, help_text='Internal notes for kitchen staff', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('closed_at', models.DateTimeField(blank=True, help_text='Closure timestamp', null=True)),
                ('booking', models.ForeignKey(blank=True, help_text='Link to guest booking for room charges', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_orders', to='bookings.booking')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_restaurant_orders', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_orders', to='hotels.hotel')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_restaurant_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=60, unique=True)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('paid', 'Paid'), ('void', 'Void')], db_index=True, default='issued', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('service_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Creation timestamp')),
                ('issued_at', models.DateTimeField(blank=True, help_text='Issuance timestamp', null=True)),
                ('paid_at', models.DateTimeField(blank=True, help_text='Payment timestamp', null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_invoices', to='hotels.hotel')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='restaurant.restaurantorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Price at time of order', max_digits=12)),
                ('note', models.CharField(blank=True, help_text='Special instructions for this item', max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='restaurant.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='restaurant.restaurantorder')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('momo', 'Mobile Money'), ('card', 'Card'), ('bank', 'Bank Transfer'), ('room', 'Room Charge')], default='cash', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('reference', models.CharField(blank=True, help_text='Transaction reference number', max_length=120, null=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Receipt timestamp')),
                ('notes', models.TextField(blank=True, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_payments', to='hotels.hotel')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='restaurant.restaurantinvoice')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Table number or identifier', max_length=30)),
                ('seats', models.PositiveIntegerField(default=4, help_text='Maximum seating capacity')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text='Special notes about the table (location, view, etc.)', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tables', to='restaurant.diningarea')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_tables', to='hotels.hotel')),
            ],
            options={
                'ordering': ['hotel__name', 'number'],
            },
        ),
        migrations.AddField(
            model_name='restaurantorder',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='restaurant.table'),
        ),
        migrations.AddIndex(
            model_name='diningarea',
            index=models.Index(fields=['hotel', 'name'], name='restaurant__hotel_i_191005_idx'),
        ),
        migrations.AddIndex(
            model_name='diningarea',
            index=models.Index(fields=['hotel', 'is_active'], name='restaurant__hotel_i_88ce96_idx'),
        ),
        migrations.AddConstraint(
            model_name='diningarea',
            constraint=models.UniqueConstraint(fields=('hotel', 'name'), name='uniq_rest_area_per_hotel'),
        ),
        migrations.AddIndex(
            model_name='menucategory',
            index=models.Index(fields=['hotel', 'is_active'], name='restaurant__hotel_i_550bc3_idx'),
        ),
        migrations.AddIndex(
            model_name='menucategory',
            index=models.Index(fields=['hotel', 'sort_order'], name='restaurant__hotel_i_2b2fb4_idx'),
        ),
        migrations.AddIndex(
            model_name='menucategory',
            index=models.Index(fields=['hotel', 'name'], name='restaurant__hotel_i_495425_idx'),
        ),
        migrations.AddConstraint(
            model_name='menucategory',
            constraint=models.UniqueConstraint(fields=('hotel', 'name'), name='uniq_menu_category_per_hotel'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['hotel', 'is_active'], name='restaurant__hotel_i_361c67_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['hotel', 'category'], name='restaurant__hotel_i_182aed_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['hotel', 'name'], name='restaurant__hotel_i_a4b111_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['hotel', 'is_featured'], name='restaurant__hotel_i_6d6856_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['hotel', 'is_recommended'], name='restaurant__hotel_i_dd17aa_idx'),
        ),
        migrations.AddConstraint(
            model_name='menuitem',
            constraint=models.UniqueConstraint(fields=('hotel', 'name'), name='uniq_menu_item_name_per_hotel'),
        ),
        migrations.AddIndex(
            model_name='restaurantinvoice',
            index=models.Index(fields=['hotel', 'status'], name='restaurant__hotel_i_d77d63_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantinvoice',
            index=models.Index(fields=['hotel', 'created_at'], name='restaurant__hotel_i_a838f2_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantinvoice',
            index=models.Index(fields=['hotel', 'invoice_number'], name='restaurant__hotel_i_d3b9d5_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantinvoice',
            index=models.Index(fields=['status', 'issued_at'], name='restaurant__status_fd23bd_idx'),
        ),
        migrations.AddConstraint(
            model_name='restaurantinvoice',
            constraint=models.UniqueConstraint(fields=('hotel', 'invoice_number'), name='uniq_rest_invoice_number_per_hotel'),
        ),
        migrations.AddIndex(
            model_name='restaurantorderitem',
            index=models.Index(fields=['order'], name='restaurant__order_i_06d139_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantorderitem',
            index=models.Index(fields=['item'], name='restaurant__item_id_38fc3e_idx'),
        ),
        migrations.AddConstraint(
            model_name='restaurantorderitem',
            constraint=models.UniqueConstraint(fields=('order', 'item'), name='uniq_rest_order_item_per_order'),
        ),
        migrations.AddIndex(
            model_name='restaurantpayment',
            index=models.Index(fields=['hotel', 'received_at'], name='restaurant__hotel_i_408b77_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantpayment',
            index=models.Index(fields=['hotel', 'method'], name='restaurant__hotel_i_33980e_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantpayment',
            index=models.Index(fields=['hotel', 'invoice'], name='restaurant__hotel_i_a2a3ed_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantpayment',
            index=models.Index(fields=['method', 'received_at'], name='restaurant__method_aa8eeb_idx'),
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(fields=['hotel', 'is_active'], name='restaurant__hotel_i_52ebf6_idx'),
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(fields=['hotel', 'area'], name='restaurant__hotel_i_355cf3_idx'),
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(fields=['hotel', 'number'], name='restaurant__hotel_i_24c70c_idx'),
        ),
        migrations.AddConstraint(
            model_name='table',
            constraint=models.UniqueConstraint(fields=('hotel', 'number'), name='uniq_rest_table_number_per_hotel'),
        ),
        migrations.AddIndex(
            model_name='restaurantorder',
            index=models.Index(fields=['hotel', 'status'], name='restaurant__hotel_i_1bda28_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantorder',
            index=models.Index(fields=['hotel', 'created_at'], name='restaurant__hotel_i_059c1c_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantorder',
            index=models.Index(fields=['hotel', 'order_number'], name='restaurant__hotel_i_bbb230_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantorder',
            index=models.Index(fields=['hotel', 'table', 'status'], name='restaurant__hotel_i_6fb9f0_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantorder',
            index=models.Index(fields=['booking', 'room_charge'], name='restaurant__booking_58458f_idx'),
        ),
    ]
