# Generated by Django 6.0.2 on 2026-02-26 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiningArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dining_areas', to='hotels.hotel')),
            ],
            options={
                'ordering': ['hotel__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_categories', to='hotels.hotel')),
            ],
            options={
                'ordering': ['hotel__name', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('track_stock', models.BooleanField(default=False)),
                ('stock_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='restaurant.menucategory')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='hotels.hotel')),
            ],
            options={
                'ordering': ['hotel__name', 'category__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('kitchen', 'In Kitchen'), ('served', 'Served'), ('billed', 'Billed'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('order_number', models.CharField(blank=True, max_length=60, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_orders', to='hotels.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=60)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('paid', 'Paid'), ('void', 'Void')], default='issued', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_invoices', to='hotels.hotel')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='restaurant.restaurantorder')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('kitchen', 'In Kitchen'), ('served', 'Served'), ('cancelled', 'Cancelled')], default='new', max_length=20)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='restaurant.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='restaurant.restaurantorder')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('momo', 'Mobile Money'), ('card', 'Card'), ('bank', 'Bank Transfer')], default='cash', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(blank=True, max_length=120, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_payments', to='hotels.hotel')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='restaurant.restaurantinvoice')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30)),
                ('seats', models.PositiveIntegerField(default=4)),
                ('is_active', models.BooleanField(default=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tables', to='restaurant.diningarea')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_tables', to='hotels.hotel')),
            ],
            options={
                'ordering': ['hotel__name', 'number'],
            },
        ),
        migrations.AddField(
            model_name='restaurantorder',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='restaurant.table'),
        ),
        migrations.AddConstraint(
            model_name='diningarea',
            constraint=models.UniqueConstraint(fields=('hotel', 'name'), name='uniq_rest_area_per_hotel'),
        ),
        migrations.AddConstraint(
            model_name='menucategory',
            constraint=models.UniqueConstraint(fields=('hotel', 'name'), name='uniq_menu_category_per_hotel'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['hotel', 'is_active'], name='restaurant__hotel_i_361c67_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['hotel', 'category'], name='restaurant__hotel_i_182aed_idx'),
        ),
        migrations.AddConstraint(
            model_name='menuitem',
            constraint=models.UniqueConstraint(fields=('hotel', 'name'), name='uniq_menu_item_name_per_hotel'),
        ),
        migrations.AddIndex(
            model_name='restaurantinvoice',
            index=models.Index(fields=['hotel', 'status'], name='restaurant__hotel_i_d77d63_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantinvoice',
            index=models.Index(fields=['hotel', 'created_at'], name='restaurant__hotel_i_a838f2_idx'),
        ),
        migrations.AddConstraint(
            model_name='restaurantinvoice',
            constraint=models.UniqueConstraint(fields=('hotel', 'invoice_number'), name='uniq_rest_invoice_number_per_hotel'),
        ),
        migrations.AddIndex(
            model_name='restaurantorderitem',
            index=models.Index(fields=['order'], name='restaurant__order_i_06d139_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantpayment',
            index=models.Index(fields=['hotel', 'received_at'], name='restaurant__hotel_i_408b77_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantpayment',
            index=models.Index(fields=['hotel', 'method'], name='restaurant__hotel_i_33980e_idx'),
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(fields=['hotel', 'is_active'], name='restaurant__hotel_i_52ebf6_idx'),
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(fields=['hotel', 'area'], name='restaurant__hotel_i_355cf3_idx'),
        ),
        migrations.AddConstraint(
            model_name='table',
            constraint=models.UniqueConstraint(fields=('hotel', 'number'), name='uniq_rest_table_number_per_hotel'),
        ),
        migrations.AddIndex(
            model_name='restaurantorder',
            index=models.Index(fields=['hotel', 'status'], name='restaurant__hotel_i_1bda28_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantorder',
            index=models.Index(fields=['hotel', 'created_at'], name='restaurant__hotel_i_059c1c_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantorder',
            index=models.Index(fields=['hotel', 'order_number'], name='restaurant__hotel_i_bbb230_idx'),
        ),
    ]
