# Generated by Django 6.0.2 on 2026-03-04 14:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
        ('restaurant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurantinvoice',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='restaurantorder',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='restaurantorderitem',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='restaurantpayment',
            options={'ordering': ['-received_at']},
        ),
        migrations.AlterField(
            model_name='restaurantinvoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('paid', 'Paid'), ('void', 'Void')], db_index=True, default='issued', max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurantorder',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('kitchen', 'In Kitchen'), ('served', 'Served'), ('billed', 'Billed'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=20),
        ),
        migrations.AddIndex(
            model_name='diningarea',
            index=models.Index(fields=['hotel', 'name'], name='restaurant__hotel_i_191005_idx'),
        ),
        migrations.AddIndex(
            model_name='menucategory',
            index=models.Index(fields=['hotel', 'is_active'], name='restaurant__hotel_i_550bc3_idx'),
        ),
        migrations.AddIndex(
            model_name='menucategory',
            index=models.Index(fields=['hotel', 'sort_order'], name='restaurant__hotel_i_2b2fb4_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['hotel', 'name'], name='restaurant__hotel_i_a4b111_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantinvoice',
            index=models.Index(fields=['hotel', 'invoice_number'], name='restaurant__hotel_i_d3b9d5_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantpayment',
            index=models.Index(fields=['hotel', 'invoice'], name='restaurant__hotel_i_a2a3ed_idx'),
        ),
    ]
