# Generated by Django 6.0.2 on 2026-07-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
