# Generated by Django 6.0.2 on 2026-03-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_restaurantinvoice_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantorderitem',
            name='status',
        ),
        migrations.AlterField(
            model_name='restaurantinvoice',
            name='status',
            field=models.CharField(choices=[('issued', 'Issued'), ('paid', 'Paid'), ('void', 'Void')], db_index=True, default='issued', max_length=20),
        ),
    ]
