# Generated by Django 6.0.2 on 2026-04-17 20:12

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_additionalcharge_options_alter_booking_options_and_more'),
        ('hotels', '0001_initial'),
        ('restaurant', '0003_remove_restaurantorderitem_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['hotel__name', 'category__sort_order', 'name']},
        ),
        migrations.AddField(
            model_name='diningarea',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Creation timestamp'),
        ),
        migrations.AddField(
            model_name='diningarea',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of the area', null=True),
        ),
        migrations.AddField(
            model_name='diningarea',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='diningarea',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last update timestamp'),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Creation timestamp'),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='description',
            field=models.TextField(blank=True, help_text='Optional category description', null=True),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last update timestamp'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cost price for profit calculation', max_digits=12),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Creation timestamp'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the item', null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='ingredients',
            field=models.TextField(blank=True, help_text='List of main ingredients', null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured on the menu'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_gluten_free',
            field=models.BooleanField(default=False, help_text='Gluten-free option'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_recommended',
            field=models.BooleanField(default=False, help_text="Chef's recommendation"),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_spicy',
            field=models.BooleanField(default=False, help_text='Contains spicy ingredients'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_vegan',
            field=models.BooleanField(default=False, help_text='Suitable for vegans'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_vegetarian',
            field=models.BooleanField(default=False, help_text='Suitable for vegetarians'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='preparation_time',
            field=models.PositiveIntegerField(default=15, help_text='Estimated preparation time in minutes'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='reorder_level',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Stock level that triggers reorder alert', max_digits=12),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last update timestamp'),
        ),
        migrations.AddField(
            model_name='restaurantinvoice',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='restaurantinvoice',
            name='paid_at',
            field=models.DateTimeField(blank=True, help_text='Payment timestamp', null=True),
        ),
        migrations.AddField(
            model_name='restaurantinvoice',
            name='service_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='restaurantinvoice',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='restaurantinvoice',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='restaurantorder',
            name='booking',
            field=models.ForeignKey(blank=True, help_text='Link to guest booking for room charges', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_orders', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='restaurantorder',
            name='customer_email',
            field=models.EmailField(blank=True, help_text='Customer email for receipts', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='restaurantorder',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='restaurantorder',
            name='kitchen_notes',
            field=models.TextField(blank=True, help_text='Internal notes for kitchen staff', null=True),
        ),
        migrations.AddField(
            model_name='restaurantorder',
            name='room_charge',
            field=models.BooleanField(default=False, help_text="Charge to guest's room"),
        ),
        migrations.AddField(
            model_name='restaurantorder',
            name='service_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Service charge amount', max_digits=12),
        ),
        migrations.AddField(
            model_name='restaurantorder',
            name='special_instructions',
            field=models.TextField(blank=True, help_text='Special requests or instructions', null=True),
        ),
        migrations.AddField(
            model_name='restaurantorder',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='restaurantorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last update timestamp'),
        ),
        migrations.AddField(
            model_name='restaurantorder',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_restaurant_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='restaurantorderitem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Creation timestamp'),
        ),
        migrations.AddField(
            model_name='restaurantorderitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last update timestamp'),
        ),
        migrations.AddField(
            model_name='restaurantpayment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Creation timestamp'),
        ),
        migrations.AddField(
            model_name='table',
            name='notes',
            field=models.TextField(blank=True, help_text='Special notes about the table (location, view, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last update timestamp'),
        ),
        migrations.AlterField(
            model_name='diningarea',
            name='name',
            field=models.CharField(help_text='e.g., Main Hall, Terrace, VIP Room', max_length=120),
        ),
        migrations.AlterField(
            model_name='menucategory',
            name='name',
            field=models.CharField(help_text='e.g., Appetizers, Main Course, Desserts, Beverages', max_length=120),
        ),
        migrations.AlterField(
            model_name='menucategory',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Available for ordering'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(help_text='Name of the dish/beverage', max_length=160),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Selling price to customers', max_digits=12),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='stock_qty',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current stock quantity', max_digits=12),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='track_stock',
            field=models.BooleanField(default=False, help_text='Enable automatic stock tracking'),
        ),
        migrations.AlterField(
            model_name='restaurantinvoice',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Creation timestamp'),
        ),
        migrations.AlterField(
            model_name='restaurantinvoice',
            name='invoice_number',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='restaurantinvoice',
            name='issued_at',
            field=models.DateTimeField(blank=True, help_text='Issuance timestamp', null=True),
        ),
        migrations.AlterField(
            model_name='restaurantorder',
            name='closed_at',
            field=models.DateTimeField(blank=True, help_text='Closure timestamp', null=True),
        ),
        migrations.AlterField(
            model_name='restaurantorder',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Creation timestamp'),
        ),
        migrations.AlterField(
            model_name='restaurantorder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_restaurant_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='restaurantorder',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Customer name for walk-ins', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='restaurantorder',
            name='customer_phone',
            field=models.CharField(blank=True, help_text='Customer contact number', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='restaurantorder',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount amount', max_digits=12),
        ),
        migrations.AlterField(
            model_name='restaurantorder',
            name='order_number',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='restaurantorder',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax amount', max_digits=12),
        ),
        migrations.AlterField(
            model_name='restaurantorderitem',
            name='note',
            field=models.CharField(blank=True, help_text='Special instructions for this item', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='restaurantorderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Price at time of order', max_digits=12),
        ),
        migrations.AlterField(
            model_name='restaurantpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='restaurantpayment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('momo', 'Mobile Money'), ('card', 'Card'), ('bank', 'Bank Transfer'), ('room', 'Room Charge')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurantpayment',
            name='received_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Receipt timestamp'),
        ),
        migrations.AlterField(
            model_name='restaurantpayment',
            name='reference',
            field=models.CharField(blank=True, help_text='Transaction reference number', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='number',
            field=models.CharField(help_text='Table number or identifier', max_length=30),
        ),
        migrations.AlterField(
            model_name='table',
            name='seats',
            field=models.PositiveIntegerField(default=4, help_text='Maximum seating capacity'),
        ),
        migrations.AddIndex(
            model_name='diningarea',
            index=models.Index(fields=['hotel', 'is_active'], name='restaurant__hotel_i_88ce96_idx'),
        ),
        migrations.AddIndex(
            model_name='menucategory',
            index=models.Index(fields=['hotel', 'name'], name='restaurant__hotel_i_495425_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['hotel', 'is_featured'], name='restaurant__hotel_i_6d6856_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['hotel', 'is_recommended'], name='restaurant__hotel_i_dd17aa_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantinvoice',
            index=models.Index(fields=['status', 'issued_at'], name='restaurant__status_fd23bd_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantorder',
            index=models.Index(fields=['hotel', 'table', 'status'], name='restaurant__hotel_i_6fb9f0_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantorder',
            index=models.Index(fields=['booking', 'room_charge'], name='restaurant__booking_58458f_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantorderitem',
            index=models.Index(fields=['item'], name='restaurant__item_id_38fc3e_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantpayment',
            index=models.Index(fields=['method', 'received_at'], name='restaurant__method_aa8eeb_idx'),
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(fields=['hotel', 'number'], name='restaurant__hotel_i_24c70c_idx'),
        ),
        migrations.AddConstraint(
            model_name='restaurantorderitem',
            constraint=models.UniqueConstraint(fields=('order', 'item'), name='uniq_rest_order_item_per_order'),
        ),
    ]
