# Generated by Django 6.0.2 on 2026-05-02 08:47

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('hotels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BarCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bar_categories', to='hotels.hotel')),
            ],
            options={
                'ordering': ['hotel__name', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('sku', models.CharField(blank=True, max_length=60, null=True)),
                ('unit', models.CharField(default='bottle', max_length=30)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('track_stock', models.BooleanField(default=True)),
                ('stock_qty', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('reorder_level', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='bar.barcategory')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bar_items', to='hotels.hotel')),
            ],
            options={
                'ordering': ['hotel__name', 'category__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BarOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(blank=True, help_text='Optional - for walk-in customers or order identification', max_length=255, null=True)),
                ('room_charge', models.BooleanField(default=False, help_text='Post to room/booking instead of immediate cash payment')),
                ('status', models.CharField(choices=[('open', 'Open'), ('served', 'Served'), ('billed', 'Billed'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=20)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('order_number', models.CharField(blank=True, max_length=60, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bar_orders', to='bookings.booking')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bar_orders', to='hotels.hotel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BarOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='bar.baritem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bar.barorder')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BarStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('opening', 'Opening Stock'), ('purchase', 'Purchase'), ('sale', 'Sale'), ('adjustment', 'Adjustment'), ('damage', 'Damage'), ('return', 'Return')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('reference', models.CharField(blank=True, max_length=120, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bar_stock_movements', to='hotels.hotel')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='bar.baritem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='barcategory',
            index=models.Index(fields=['hotel', 'is_active'], name='bar_barcate_hotel_i_0ac715_idx'),
        ),
        migrations.AddIndex(
            model_name='barcategory',
            index=models.Index(fields=['hotel', 'sort_order'], name='bar_barcate_hotel_i_ba15cd_idx'),
        ),
        migrations.AddConstraint(
            model_name='barcategory',
            constraint=models.UniqueConstraint(fields=('hotel', 'name'), name='uniq_bar_category_per_hotel'),
        ),
        migrations.AddIndex(
            model_name='baritem',
            index=models.Index(fields=['hotel', 'category'], name='bar_baritem_hotel_i_888232_idx'),
        ),
        migrations.AddIndex(
            model_name='baritem',
            index=models.Index(fields=['hotel', 'is_active'], name='bar_baritem_hotel_i_508cf9_idx'),
        ),
        migrations.AddIndex(
            model_name='baritem',
            index=models.Index(fields=['hotel', 'name'], name='bar_baritem_hotel_i_ea0742_idx'),
        ),
        migrations.AddIndex(
            model_name='baritem',
            index=models.Index(fields=['hotel', 'sku'], name='bar_baritem_hotel_i_f30464_idx'),
        ),
        migrations.AddConstraint(
            model_name='baritem',
            constraint=models.UniqueConstraint(fields=('hotel', 'name'), name='uniq_bar_item_name_per_hotel'),
        ),
        migrations.AddIndex(
            model_name='barorder',
            index=models.Index(fields=['hotel', 'status'], name='bar_barorde_hotel_i_db5984_idx'),
        ),
        migrations.AddIndex(
            model_name='barorder',
            index=models.Index(fields=['hotel', 'created_at'], name='bar_barorde_hotel_i_f75813_idx'),
        ),
        migrations.AddIndex(
            model_name='barorder',
            index=models.Index(fields=['hotel', 'order_number'], name='bar_barorde_hotel_i_5b9dc2_idx'),
        ),
        migrations.AddIndex(
            model_name='barorderitem',
            index=models.Index(fields=['order'], name='bar_barorde_order_i_9adeef_idx'),
        ),
        migrations.AddIndex(
            model_name='barstockmovement',
            index=models.Index(fields=['hotel', 'item'], name='bar_barstoc_hotel_i_86ab59_idx'),
        ),
        migrations.AddIndex(
            model_name='barstockmovement',
            index=models.Index(fields=['hotel', 'movement_type'], name='bar_barstoc_hotel_i_ca9bf7_idx'),
        ),
        migrations.AddIndex(
            model_name='barstockmovement',
            index=models.Index(fields=['hotel', 'created_at'], name='bar_barstoc_hotel_i_62f466_idx'),
        ),
    ]
