# Generated by Django 6.0.2 on 2026-05-04 07:16

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0001_initial'),
        ('bookings', '0001_initial'),
        ('hotels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barcategory',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Bar Category', 'verbose_name_plural': 'Bar Categories'},
        ),
        migrations.AlterModelOptions(
            name='baritem',
            options={'ordering': ['category__sort_order', 'name'], 'verbose_name': 'Bar Item', 'verbose_name_plural': 'Bar Items'},
        ),
        migrations.AlterModelOptions(
            name='barorder',
            options={'ordering': ['-created_at'], 'verbose_name': 'Bar Order', 'verbose_name_plural': 'Bar Orders'},
        ),
        migrations.AlterModelOptions(
            name='barorderitem',
            options={'ordering': ['id'], 'verbose_name': 'Bar Order Item', 'verbose_name_plural': 'Bar Order Items'},
        ),
        migrations.AlterModelOptions(
            name='barstockmovement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Bar Stock Movement', 'verbose_name_plural': 'Bar Stock Movements'},
        ),
        migrations.RemoveIndex(
            model_name='barorder',
            name='bar_barorde_hotel_i_db5984_idx',
        ),
        migrations.RemoveIndex(
            model_name='barstockmovement',
            name='bar_barstoc_hotel_i_86ab59_idx',
        ),
        migrations.RemoveIndex(
            model_name='barstockmovement',
            name='bar_barstoc_hotel_i_ca9bf7_idx',
        ),
        migrations.AddField(
            model_name='barcategory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Creation timestamp'),
        ),
        migrations.AddField(
            model_name='barcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last update timestamp'),
        ),
        migrations.AddField(
            model_name='baritem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Creation timestamp'),
        ),
        migrations.AddField(
            model_name='baritem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last update timestamp'),
        ),
        migrations.AddField(
            model_name='barorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddField(
            model_name='barorderitem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='barorderitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='barcategory',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Inactive categories won't appear in item selection"),
        ),
        migrations.AlterField(
            model_name='barcategory',
            name='name',
            field=models.CharField(help_text='Category name (e.g., Beer, Wine, Spirits)', max_length=120),
        ),
        migrations.AlterField(
            model_name='barcategory',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first'),
        ),
        migrations.AlterField(
            model_name='baritem',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cost price for profit calculation', max_digits=12),
        ),
        migrations.AlterField(
            model_name='baritem',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Available for ordering'),
        ),
        migrations.AlterField(
            model_name='baritem',
            name='name',
            field=models.CharField(help_text='Name of the beverage', max_length=160),
        ),
        migrations.AlterField(
            model_name='baritem',
            name='reorder_level',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Stock level that triggers low stock alert', max_digits=12),
        ),
        migrations.AlterField(
            model_name='baritem',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, help_text='Selling price to customers', max_digits=12),
        ),
        migrations.AlterField(
            model_name='baritem',
            name='sku',
            field=models.CharField(blank=True, help_text='Stock keeping unit / barcode', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='baritem',
            name='stock_qty',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current stock quantity', max_digits=12),
        ),
        migrations.AlterField(
            model_name='baritem',
            name='track_stock',
            field=models.BooleanField(default=True, help_text='Enable automatic stock tracking'),
        ),
        migrations.AlterField(
            model_name='baritem',
            name='unit',
            field=models.CharField(default='bottle', help_text='Unit of measurement (bottle, can, glass, etc.)', max_length=30),
        ),
        migrations.AlterField(
            model_name='barorder',
            name='booking',
            field=models.ForeignKey(blank=True, help_text='Link to guest booking for room charges', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bar_orders', to='bookings.booking'),
        ),
        migrations.AlterField(
            model_name='barorder',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='barorder',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount amount', max_digits=12),
        ),
        migrations.AlterField(
            model_name='barorder',
            name='guest_name',
            field=models.CharField(blank=True, help_text='For walk-in customers or order identification', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='barorder',
            name='order_number',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='barorder',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax amount', max_digits=12),
        ),
        migrations.AlterField(
            model_name='barorderitem',
            name='note',
            field=models.CharField(blank=True, help_text='Special instructions for this item', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='barorderitem',
            name='qty',
            field=models.PositiveIntegerField(default=1, help_text='Quantity ordered'),
        ),
        migrations.AlterField(
            model_name='barorderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Price at time of order (snapshot)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='barstockmovement',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Stock balance after movement', max_digits=12),
        ),
        migrations.AlterField(
            model_name='barstockmovement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='barstockmovement',
            name='movement_type',
            field=models.CharField(choices=[('opening', 'Opening Stock'), ('purchase', 'Purchase'), ('sale', 'Sale'), ('adjustment', 'Adjustment'), ('damage', 'Damage'), ('return', 'Return')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='barstockmovement',
            name='note',
            field=models.TextField(blank=True, help_text='Additional notes about the movement', null=True),
        ),
        migrations.AlterField(
            model_name='barstockmovement',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Positive for in, negative for out', max_digits=12),
        ),
        migrations.AlterField(
            model_name='barstockmovement',
            name='reference',
            field=models.CharField(blank=True, help_text='Order number or purchase reference', max_length=120, null=True),
        ),
        migrations.AddIndex(
            model_name='barcategory',
            index=models.Index(fields=['hotel', 'name'], name='bar_barcate_hotel_i_d9ec4c_idx'),
        ),
        migrations.AddIndex(
            model_name='baritem',
            index=models.Index(fields=['hotel', 'track_stock', 'stock_qty'], name='bar_baritem_hotel_i_65478b_idx'),
        ),
        migrations.AddIndex(
            model_name='barorder',
            index=models.Index(fields=['hotel', 'status', '-created_at'], name='bar_barorde_hotel_i_8716ca_idx'),
        ),
        migrations.AddIndex(
            model_name='barorder',
            index=models.Index(fields=['booking', 'room_charge'], name='bar_barorde_booking_776c7f_idx'),
        ),
        migrations.AddIndex(
            model_name='barorderitem',
            index=models.Index(fields=['item'], name='bar_barorde_item_id_81f35c_idx'),
        ),
        migrations.AddIndex(
            model_name='barstockmovement',
            index=models.Index(fields=['hotel', 'item', '-created_at'], name='bar_barstoc_hotel_i_dc1ed9_idx'),
        ),
        migrations.AddIndex(
            model_name='barstockmovement',
            index=models.Index(fields=['hotel', 'movement_type', '-created_at'], name='bar_barstoc_hotel_i_87002d_idx'),
        ),
        migrations.AddIndex(
            model_name='barstockmovement',
            index=models.Index(fields=['reference'], name='bar_barstoc_referen_dc11f1_idx'),
        ),
        migrations.AddConstraint(
            model_name='baritem',
            constraint=models.UniqueConstraint(condition=models.Q(('sku__isnull', False)), fields=('hotel', 'sku'), name='uniq_bar_item_sku_per_hotel'),
        ),
        migrations.AddConstraint(
            model_name='barorderitem',
            constraint=models.UniqueConstraint(fields=('order', 'item'), name='uniq_bar_order_item_per_order'),
        ),
    ]
