# Generated by Django 6.0.2 on 2026-07-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0002_alter_barcategory_options_alter_baritem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcategory',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='baritem',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
