# Generated by Django 6.0.2 on 2026-02-26 07:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('full_name', models.CharField(db_index=True, max_length=255)),
                ('preferred_name', models.CharField(blank=True, max_length=100, null=True)),
                ('guest_type', models.CharField(choices=[('individual', 'Individual'), ('corporate', 'Corporate'), ('travel_agency', 'Travel Agency'), ('tour_operator', 'Tour Operator'), ('vip', 'VIP')], db_index=True, default='individual', max_length=20)),
                ('phone', models.CharField(db_index=True, max_length=30)),
                ('alternative_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('id_type', models.CharField(blank=True, choices=[('passport', 'Passport'), ('national_id', 'National ID'), ('drivers_license', "Driver's License"), ('other', 'Other')], max_length=20, null=True)),
                ('id_number', models.CharField(blank=True, max_length=120, null=True)),
                ('id_issue_date', models.DateField(blank=True, null=True)),
                ('id_expiry_date', models.DateField(blank=True, null=True)),
                ('id_scan', models.FileField(blank=True, null=True, upload_to='guest_ids/%Y/%m/')),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('nationality', models.CharField(blank=True, max_length=120, null=True)),
                ('language', models.CharField(default='en', max_length=10)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_vat', models.CharField(blank=True, max_length=50, null=True)),
                ('company_address', models.TextField(blank=True, null=True)),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('dietary_restrictions', models.TextField(blank=True, null=True)),
                ('room_preferences', models.TextField(blank=True, null=True)),
                ('is_vip', models.BooleanField(db_index=True, default=False)),
                ('marketing_consent', models.BooleanField(default=False)),
                ('newsletter_subscribed', models.BooleanField(default=False)),
                ('is_blacklisted', models.BooleanField(db_index=True, default=False)),
                ('blacklist_reason', models.TextField(blank=True, null=True)),
                ('blacklisted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blacklisted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blacklisted_guests', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_guests', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='hotels.hotel')),
            ],
            options={
                'verbose_name': 'Guest',
                'verbose_name_plural': 'Guests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('confirmation_code', models.CharField(blank=True, max_length=50, null=True)),
                ('source', models.CharField(choices=[('direct', 'Direct'), ('walk_in', 'Walk-in'), ('ota', 'Online Travel Agency'), ('corporate', 'Corporate'), ('travel_agent', 'Travel Agent'), ('phone', 'Phone'), ('email', 'Email'), ('website', 'Website'), ('mobile_app', 'Mobile App')], default='direct', max_length=20)),
                ('source_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('check_in', models.DateField(db_index=True)),
                ('check_out', models.DateField(db_index=True)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('adults', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('children', models.PositiveIntegerField(default=0)),
                ('infants', models.PositiveIntegerField(default=0)),
                ('nightly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('extra_bed_charge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='fixed', max_length=20)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('provisional', 'Provisional'), ('reserved', 'Reserved'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('cancelled', 'Cancelled'), ('no_show', 'No Show'), ('waitlist', 'Waitlist')], db_index=True, default='reserved', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('guest_notes', models.TextField(blank=True, null=True)),
                ('internal_notes', models.TextField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('cancellation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_bookings', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bookings', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='hotels.hotel')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='rooms.room')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.guest')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-check_in', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdditionalCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('mini_bar', 'Mini Bar'), ('restaurant', 'Restaurant'), ('laundry', 'Laundry'), ('spa', 'Spa'), ('transport', 'Transport'), ('other', 'Other')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_charges', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Additional Charge',
                'verbose_name_plural': 'Additional Charges',
                'indexes': [models.Index(fields=['booking', 'category'], name='bookings_ad_booking_b1d064_idx')],
            },
        ),
        migrations.CreateModel(
            name='BookingAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('check_in', 'Checked In'), ('check_out', 'Checked Out'), ('cancel', 'Cancelled'), ('modify_dates', 'Dates Modified'), ('modify_room', 'Room Modified'), ('add_charge', 'Additional Charge'), ('add_payment', 'Payment Added')], max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='bookings.booking')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking Audit Log',
                'verbose_name_plural': 'Booking Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['booking', '-created_at'], name='bookings_bo_booking_02a245_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['hotel', 'full_name'], name='bookings_gu_hotel_i_fe2dd5_idx'),
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['hotel', 'phone'], name='bookings_gu_hotel_i_69336f_idx'),
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['hotel', 'email'], name='bookings_gu_hotel_i_916f8e_idx'),
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['hotel', 'guest_type'], name='bookings_gu_hotel_i_952f5a_idx'),
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['hotel', 'is_blacklisted'], name='bookings_gu_hotel_i_752050_idx'),
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['hotel', 'created_at'], name='bookings_gu_hotel_i_122e47_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['hotel', 'status', 'check_in'], name='bookings_bo_hotel_i_70bd81_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['hotel', 'payment_status'], name='bookings_bo_hotel_i_0843b5_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['hotel', 'check_in', 'check_out'], name='bookings_bo_hotel_i_7dad80_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_number'], name='bookings_bo_booking_03d631_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['guest', 'check_in'], name='bookings_bo_guest_i_186f15_idx'),
        ),
    ]
