# Generated by Django 6.0.2 on 2026-03-04 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_additionalcharge_total'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalcharge',
            options={},
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-check_in', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='bookingauditlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='guest',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='guest',
            name='bookings_gu_hotel_i_122e47_idx',
        ),
        migrations.AddField(
            model_name='booking',
            name='use_room_rate',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='additionalcharge',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookingauditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('check_in', 'Checked In'), ('check_out', 'Checked Out'), ('cancel', 'Cancelled'), ('add_charge', 'Additional Charge'), ('add_payment', 'Payment Added')], max_length=30),
        ),
        migrations.AlterField(
            model_name='bookingauditlog',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
