# Generated by Django 6.0.2 on 2026-05-19 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_guest_user'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='guest',
            name='bookings_gu_user_id_idx',
        ),
    ]
